"""
Natural Driver Controller Module

Python adaptation of esmini's ControllerNaturalDriver.
Provides IDM-based longitudinal control and lane-change decision output.

Simple API:
    controller = NaturalDriverController(ego_id=0, rm_lib=rm_lib)
    controller.set_desired_speed(20.0)

    # In control loop:
    output = controller.update(ground_truth, dt)
    throttle, brake = output.throttle, output.brake
    if output.lane_change_request:
        # Apply lane change with your own integration layer
        pass
"""

import math
from dataclasses import dataclass
from enum import Enum
from typing import Dict, List, Optional, Tuple, TYPE_CHECKING

from .vehicle_state import VehicleState, VehicleStateExtractor

if TYPE_CHECKING:
    from .rm_lib import EsminiRMLib


SMALL_NUMBER = 1e-6


class NaturalDriverState(Enum):
    """NaturalDriver state machine."""
    DRIVE = 0
    CHANGE_LANE = 1


class VehicleOfInterestType(Enum):
    """Vehicle-of-interest buckets."""
    LEAD = 0
    FOLLOWING = 1
    LEFT_LEAD = 2
    LEFT_FOLLOW = 3
    RIGHT_LEAD = 4
    RIGHT_FOLLOW = 5


@dataclass
class NaturalDriverConfig:
    """
    Configuration for NaturalDriver controller.

    Values are based on ControllerNaturalDriver.cpp defaults.
    """
    desired_distance: float = 20.0
    desired_speed: float = 15.0
    lane_change_duration: float = 3.0
    lookahead_dist: float = 115.0
    max_deceleration: float = 3.0  # positive magnitude
    max_acceleration: float = 3.0
    lane_change_delay: float = 1.0
    desired_thw: float = 2.0
    max_imposed_braking: float = 3.0
    politeness: float = 0.5
    lane_change_acc_gain: float = 0.2
    route_lane_id: int = -1

    # Output conversion (acceleration -> throttle/brake)
    acc_to_throttle_gain: float = 0.30
    acc_to_brake_gain: float = 0.25

    # Fallback when no valid bbox length is available
    default_half_length: float = 2.5


DEFAULT_NATURAL_DRIVER_CONFIG = NaturalDriverConfig()


@dataclass
class LaneChangeRequest:
    """Lane-change request generated by the controller."""
    target_lane_id: int
    direction: str  # 'left' or 'right'
    duration: float
    indicator: int  # 0=off, 1=left, 2=right


@dataclass
class NaturalDriverOutput:
    """Output from NaturalDriverController."""
    throttle: float
    brake: float
    acceleration: float
    current_speed: float
    state: NaturalDriverState
    lane_change_request: Optional[LaneChangeRequest] = None
    lead_vehicle_id: Optional[int] = None

    @property
    def indicator(self) -> int:
        """Indicator output helper (0=off,1=left,2=right)."""
        if self.lane_change_request is None:
            return 0
        return self.lane_change_request.indicator


@dataclass
class _DetectedVehicle:
    obj_id: int
    x: float
    y: float
    z: float
    h: float
    speed: float
    half_length: float
    road_id: int
    lane_id: int
    s: float
    lane_offset: float
    ds_ego: float
    dt_ego: float
    d_lane_id: int


class NaturalDriverController:
    """
    Python adaptation of esmini ControllerNaturalDriver.

    Features:
    - IDM longitudinal acceleration model
    - Merging/lane-change decision similar to MOBIL criteria
    - Optional RoadManager support for lane-accurate neighbor detection

    Note:
    This controller outputs lane-change requests. Applying the actual lane
    change action is delegated to the caller/system integration.
    """

    def __init__(
        self,
        ego_id: int = 0,
        config: Optional[NaturalDriverConfig] = None,
        rm_lib: Optional['EsminiRMLib'] = None
    ):
        self.config = config or DEFAULT_NATURAL_DRIVER_CONFIG
        self._rm_lib = rm_lib
        self._state_extractor = VehicleStateExtractor(ego_id)

        self._target_pos_handle: int = -1

        self._state = NaturalDriverState.DRIVE
        self._desired_speed = self.config.desired_speed
        self._current_speed = self.config.desired_speed
        self._lane_ids_available: Tuple[int, int] = (0, 0)
        self._vehicles_in_radius: List[_DetectedVehicle] = []
        self._voi: Dict[VehicleOfInterestType, Optional[_DetectedVehicle]] = {
            t: None for t in VehicleOfInterestType
        }
        self._lane_change_injected = False
        self._lane_change_cooldown = self.config.lane_change_duration + self.config.lane_change_delay
        self._target_lane = 0
        self._initiate_lane_change = False
        self._last_output: Optional[NaturalDriverOutput] = None

    @property
    def state(self) -> NaturalDriverState:
        return self._state

    @property
    def desired_speed(self) -> float:
        return self._desired_speed

    @property
    def lane_change_injected(self) -> bool:
        return self._lane_change_injected

    def set_desired_speed(self, speed: float) -> None:
        self._desired_speed = max(0.0, speed)

    def reset(self) -> None:
        self._state = NaturalDriverState.DRIVE
        self._current_speed = self._desired_speed
        self._lane_ids_available = (0, 0)
        self._vehicles_in_radius = []
        self._voi = {t: None for t in VehicleOfInterestType}
        self._lane_change_injected = False
        self._lane_change_cooldown = self.config.lane_change_duration + self.config.lane_change_delay
        self._target_lane = 0
        self._initiate_lane_change = False
        self._last_output = None

    def update(self, ground_truth, dt: float) -> NaturalDriverOutput:
        """
        Update controller from OSI GroundTruth.

        Args:
            ground_truth: OSI GroundTruth
            dt: Time step [s]

        Returns:
            NaturalDriverOutput with throttle/brake and optional lane-change request.
        """
        if dt <= 0:
            out = NaturalDriverOutput(
                throttle=0.0,
                brake=0.0,
                acceleration=0.0,
                current_speed=max(0.0, self._current_speed),
                state=self._state,
            )
            self._last_output = out
            return out

        ego_state = self._state_extractor.extract(ground_truth)
        if ego_state is None:
            out = NaturalDriverOutput(
                throttle=0.0,
                brake=0.0,
                acceleration=0.0,
                current_speed=max(0.0, self._current_speed),
                state=self._state,
            )
            self._last_output = out
            return out

        if self._rm_lib is not None:
            ego_state = self._state_extractor.enrich_with_road_data(ego_state, self._rm_lib)

        self._current_speed = ego_state.speed
        ego_vehicle = self._make_ego_vehicle(ground_truth, ego_state)

        self._update_surrounding_vehicles(ground_truth, ego_state)

        lead = self._voi[VehicleOfInterestType.LEAD]
        acceleration = self._get_acceleration(ego_vehicle, lead)
        acceleration = max(-self.config.max_deceleration, acceleration)

        lane_change_request: Optional[LaneChangeRequest] = None

        if self._state == NaturalDriverState.DRIVE:
            if not self._lane_change_injected and self._adjacent_lanes_available(ego_state):
                for lane_id in self._lane_ids_available:
                    if lane_id == 0:
                        continue
                    self._initiate_lane_change = self._check_lane_change_possible(ego_vehicle, lane_id)
                    if self._initiate_lane_change and ego_state.speed > 0.0:
                        self._target_lane = lane_id
                        self._state = NaturalDriverState.CHANGE_LANE
                        break

        if self._initiate_lane_change:
            if self._abort_lane_change(ego_vehicle):
                self._target_lane = 0
                self._state = NaturalDriverState.DRIVE
            else:
                self._lane_change_injected = True
                lane_change_request = self._build_lane_change_request(ego_state.lane_id, self._target_lane)
            self._initiate_lane_change = False

        if self._lane_change_injected:
            self._lane_change_cooldown -= dt
            if self._state == NaturalDriverState.CHANGE_LANE and self._lane_change_cooldown <= self.config.lane_change_delay:
                self._target_lane = 0
                self._state = NaturalDriverState.DRIVE
            if self._lane_change_cooldown < 0.0:
                self._lane_change_cooldown = self.config.lane_change_duration + self.config.lane_change_delay
                self._lane_change_injected = False

        self._current_speed = max(0.0, min(self._desired_speed, ego_state.speed + acceleration * dt))
        output = self._acc_to_output(acceleration)
        lead_id = lead.obj_id if lead is not None else None

        out = NaturalDriverOutput(
            throttle=output[0],
            brake=output[1],
            acceleration=acceleration,
            current_speed=self._current_speed,
            state=self._state,
            lane_change_request=lane_change_request,
            lead_vehicle_id=lead_id,
        )
        self._last_output = out
        return out

    def _make_ego_vehicle(self, ground_truth, ego_state: VehicleState) -> _DetectedVehicle:
        half_len = self.config.default_half_length
        if ground_truth is not None and len(ground_truth.moving_object) > 0:
            dim = ground_truth.moving_object[0].base.dimension
            if dim.length > 0:
                half_len = dim.length / 2.0

        return _DetectedVehicle(
            obj_id=-1,
            x=ego_state.x,
            y=ego_state.y,
            z=ego_state.z,
            h=ego_state.h,
            speed=ego_state.speed,
            half_length=half_len,
            road_id=ego_state.road_id,
            lane_id=ego_state.lane_id,
            s=ego_state.s,
            lane_offset=ego_state.lane_offset,
            ds_ego=0.0,
            dt_ego=0.0,
            d_lane_id=0,
        )

    def _update_surrounding_vehicles(self, ground_truth, ego_state: VehicleState) -> None:
        self._voi = {t: None for t in VehicleOfInterestType}
        self._vehicles_in_radius = []
        if ground_truth is None:
            return

        for idx, obj in enumerate(ground_truth.moving_object):
            if idx == 0:
                continue

            pos = obj.base.position
            ori = obj.base.orientation
            vel = obj.base.velocity
            dim = obj.base.dimension

            speed = math.sqrt(vel.x * vel.x + vel.y * vel.y)
            distance = math.sqrt((pos.x - ego_state.x) ** 2 + (pos.y - ego_state.y) ** 2)
            if distance > self.config.lookahead_dist:
                continue

            ds, dt = self._transform_to_ego_frame(ego_state.x, ego_state.y, ego_state.h, pos.x, pos.y)
            if abs(ds) > self.config.lookahead_dist:
                continue

            road_id = -1
            lane_id = 0
            s = ds
            lane_offset = dt
            if self._rm_lib is not None:
                road_id, lane_id, s, lane_offset = self._query_road_coordinates(pos.x, pos.y, pos.z, ori.yaw)
                if road_id >= 0 and ego_state.road_id >= 0 and road_id == ego_state.road_id:
                    ds = s - ego_state.s
                    dt = lane_offset - ego_state.lane_offset

            if lane_id != 0 and ego_state.lane_id != 0:
                d_lane_id = lane_id - ego_state.lane_id
            else:
                d_lane_id = 0

            half_len = dim.length / 2.0 if dim.length > 0 else self.config.default_half_length
            veh = _DetectedVehicle(
                obj_id=obj.id.value,
                x=pos.x,
                y=pos.y,
                z=pos.z,
                h=ori.yaw,
                speed=speed,
                half_length=half_len,
                road_id=road_id,
                lane_id=lane_id,
                s=s,
                lane_offset=lane_offset,
                ds_ego=ds,
                dt_ego=dt,
                d_lane_id=d_lane_id,
            )
            self._vehicles_in_radius.append(veh)
            self._classify_vehicle_of_interest(veh, ego_state.lane_id)

    def _classify_vehicle_of_interest(self, veh: _DetectedVehicle, ego_lane_id: int) -> None:
        if veh.d_lane_id == 0:
            self._find_closest_ahead(veh, VehicleOfInterestType.LEAD)
            self._find_closest_behind(veh, VehicleOfInterestType.FOLLOWING)
            return

        lane_sign = self._lane_sign(ego_lane_id)
        left_relation = veh.d_lane_id * -lane_sign == 1
        right_relation = veh.d_lane_id * -lane_sign == -1

        if left_relation:
            self._find_closest_ahead(veh, VehicleOfInterestType.LEFT_LEAD)
            self._find_closest_behind(veh, VehicleOfInterestType.LEFT_FOLLOW)
        elif right_relation:
            self._find_closest_ahead(veh, VehicleOfInterestType.RIGHT_LEAD)
            self._find_closest_behind(veh, VehicleOfInterestType.RIGHT_FOLLOW)

    def _find_closest_ahead(self, veh: _DetectedVehicle, voi_type: VehicleOfInterestType) -> None:
        current = self._voi[voi_type]
        if veh.ds_ego < 0.0:
            return
        if current is None or veh.ds_ego < current.ds_ego:
            self._voi[voi_type] = veh

    def _find_closest_behind(self, veh: _DetectedVehicle, voi_type: VehicleOfInterestType) -> None:
        current = self._voi[voi_type]
        if veh.ds_ego >= 0.0:
            return
        if current is None or veh.ds_ego > current.ds_ego:
            self._voi[voi_type] = veh

    def _adjacent_lanes_available(self, ego_state: VehicleState) -> bool:
        self._lane_ids_available = (0, 0)
        if self._rm_lib is None or ego_state.road_id < 0 or ego_state.lane_id == 0:
            return False

        n_lanes = self._rm_lib.GetRoadNumberOfDrivableLanes(ego_state.road_id, ego_state.s)
        if n_lanes <= 1:
            return False

        drivable = set()
        for idx in range(n_lanes):
            res, lane_id = self._rm_lib.GetDrivableLaneIdByIndex(ego_state.road_id, idx, ego_state.s)
            if res == 0:
                drivable.add(lane_id)

        if ego_state.lane_id not in drivable:
            return False

        lane_sign = self._lane_sign(ego_state.lane_id)
        left_lane = ego_state.lane_id - lane_sign
        right_lane = ego_state.lane_id + lane_sign

        left_driving = left_lane in drivable
        right_driving = right_lane in drivable

        if (not left_driving) and right_driving:
            self._lane_ids_available = (0, right_lane)
        elif left_driving and right_driving:
            self._lane_ids_available = (left_lane, right_lane)
        elif left_driving and (not right_driving):
            self._lane_ids_available = (left_lane, 0)
        else:
            self._lane_ids_available = (0, 0)

        return self._lane_ids_available != (0, 0)

    def _check_lane_change_possible(self, ego: _DetectedVehicle, lane_id: int) -> bool:
        if self._lane_change_injected:
            return False

        adj_lead_type, adj_follow_type = self._get_adjacent_voi_types(lane_id)
        adj_lead = self._voi[adj_lead_type]
        adj_follow = self._voi[adj_follow_type]

        new_following_pred_acc = self._get_acceleration(adj_follow, ego)
        if new_following_pred_acc < -self.config.max_imposed_braking:
            return False

        predicted_new_acc = self._get_acceleration(ego, adj_lead)
        if lane_id == self.config.route_lane_id:
            if predicted_new_acc < -self.config.max_imposed_braking:
                return False
        else:
            acc = self._get_acceleration(ego, self._voi[VehicleOfInterestType.LEAD])
            old_following_acc = self._get_acceleration(self._voi[VehicleOfInterestType.FOLLOWING], ego)
            old_following_pred_acc = self._get_acceleration(
                self._voi[VehicleOfInterestType.FOLLOWING], self._voi[VehicleOfInterestType.LEAD]
            )
            new_following_acc = self._get_acceleration(adj_follow, adj_lead)

            jerk = (
                predicted_new_acc
                - acc
                + self.config.politeness
                * (
                    new_following_pred_acc
                    - new_following_acc
                    + old_following_pred_acc
                    - old_following_acc
                )
            )
            if jerk <= self.config.lane_change_acc_gain + SMALL_NUMBER:
                return False

        return True

    def _abort_lane_change(self, ego: _DetectedVehicle) -> bool:
        if self._target_lane == 0:
            return False
        return not self._check_lane_change_possible(ego, self._target_lane)

    def _get_adjacent_voi_types(self, lane_id: int) -> Tuple[VehicleOfInterestType, VehicleOfInterestType]:
        if lane_id == self._lane_ids_available[0]:
            return VehicleOfInterestType.LEFT_LEAD, VehicleOfInterestType.LEFT_FOLLOW
        return VehicleOfInterestType.RIGHT_LEAD, VehicleOfInterestType.RIGHT_FOLLOW

    def _get_acceleration(self, follow: Optional[_DetectedVehicle], lead: Optional[_DetectedVehicle]) -> float:
        if follow is None:
            return 0.0

        desired_speed = max(self._desired_speed, 0.1)
        delta = 4
        v = max(0.0, follow.speed)
        acc = self.config.max_acceleration * (1.0 - math.pow(v / desired_speed, delta))

        if lead is not None:
            desired_gap = self._get_desired_gap(
                self.config.max_acceleration,
                self.config.max_deceleration,
                follow.speed,
                lead.speed,
                self.config.desired_distance,
                self.config.desired_thw,
            )
            ds = self._relative_longitudinal_distance(follow, lead)
            freespace = self._estimate_freespace(follow, lead, ds)
            if abs(freespace) < SMALL_NUMBER:
                freespace = SMALL_NUMBER
            acc -= self.config.max_acceleration * math.pow(desired_gap / freespace, 2.0)

        return acc

    def _get_desired_gap(
        self,
        max_acceleration: float,
        max_deceleration: float,
        follow_speed: float,
        lead_speed: float,
        desired_distance: float,
        desired_thw: float,
    ) -> float:
        ab = max(max_acceleration * max_deceleration, SMALL_NUMBER)
        relative_speed = follow_speed - lead_speed
        dynamic = follow_speed * desired_thw + follow_speed * relative_speed / (2.0 * math.sqrt(ab))
        return desired_distance + max(0.0, dynamic)

    def _estimate_freespace(self, follow: _DetectedVehicle, target: _DetectedVehicle, ds: float) -> float:
        d_heading = self._abs_angle_diff(follow.h, target.h)
        if d_heading < (math.pi / 2.0):
            if ds > 0:
                adjusted = ds - (follow.half_length + target.half_length)
                return max(0.0, adjusted)
            adjusted = ds + (follow.half_length + target.half_length)
            return min(0.0, adjusted)
        return ds

    def _relative_longitudinal_distance(self, follow: _DetectedVehicle, target: _DetectedVehicle) -> float:
        if follow.road_id >= 0 and target.road_id >= 0 and follow.road_id == target.road_id:
            return target.s - follow.s
        ds, _ = self._transform_to_ego_frame(follow.x, follow.y, follow.h, target.x, target.y)
        return ds

    def _build_lane_change_request(self, current_lane_id: int, target_lane_id: int) -> LaneChangeRequest:
        lane_sign = self._lane_sign(current_lane_id)
        delta = target_lane_id - current_lane_id
        is_left = delta * -lane_sign == 1
        direction = "left" if is_left else "right"
        indicator = 1 if is_left else 2
        return LaneChangeRequest(
            target_lane_id=target_lane_id,
            direction=direction,
            duration=self.config.lane_change_duration,
            indicator=indicator,
        )

    def _query_road_coordinates(self, x: float, y: float, z: float, h: float) -> Tuple[int, int, float, float]:
        if self._rm_lib is None:
            return -1, 0, 0.0, 0.0

        if self._target_pos_handle < 0:
            self._target_pos_handle = self._rm_lib.CreatePosition()
            if self._target_pos_handle < 0:
                return -1, 0, 0.0, 0.0

        res = self._rm_lib.SetWorldXYZHPosition(self._target_pos_handle, x, y, z, h)
        if res < 0:
            return -1, 0, 0.0, 0.0
        res, data = self._rm_lib.GetPositionData(self._target_pos_handle)
        if res < 0:
            return -1, 0, 0.0, 0.0
        return int(data.roadId), int(data.laneId), float(data.s), float(data.laneOffset)

    def _transform_to_ego_frame(
        self, ego_x: float, ego_y: float, ego_h: float, target_x: float, target_y: float
    ) -> Tuple[float, float]:
        dx = target_x - ego_x
        dy = target_y - ego_y
        c = math.cos(-ego_h)
        s = math.sin(-ego_h)
        ds = dx * c - dy * s
        dt = dx * s + dy * c
        return ds, dt

    def _acc_to_output(self, acc: float) -> Tuple[float, float]:
        if acc >= 0.0:
            throttle = min(1.0, acc * self.config.acc_to_throttle_gain)
            return throttle, 0.0
        brake = min(1.0, -acc * self.config.acc_to_brake_gain)
        return 0.0, brake

    @staticmethod
    def _lane_sign(lane_id: int) -> int:
        return 1 if lane_id > 0 else -1

    @staticmethod
    def _abs_angle_diff(a: float, b: float) -> float:
        d = a - b
        while d > math.pi:
            d -= 2.0 * math.pi
        while d < -math.pi:
            d += 2.0 * math.pi
        return abs(d)
