#!/usr/bin/env python3
"""Generate the OdrCoverageAudit whitelist include from parser_coverage.yaml.

Plan reference: GT_esmini/docs/archive/odr_1619_program/opendrive_16_19_support_plan.md P1 (OdrCoverageAudit, §3.3).

The ground truth is GT_esmini/test/odr_fixtures/parser_coverage.yaml: the (element path,
attribute set) pairs that GT_RoadManager.cpp reads on the xodr parse path, plus the small set
of whitelist-only intermediate containers documented there. This script emits a sorted,
constexpr-friendly C++ table (struct { const char* path; const char* attrs_csv; }[]) that the
audit code binary-searches by path (std::lower_bound) and then membership-tests attributes
against the comma-separated attrs_csv.

Run with the project venv:
  E:\\Repository\\GT_esmini\\esmini\\DriverScript\\.venv\\Scripts\\python.exe \\
    GT_esmini/scripts/gen_odr_whitelist.py

Output (checked in): GT_esmini/src/road/odr_side/OdrCoverageWhitelist.inc
"""

import os
import sys

try:
    import yaml
except ImportError:
    sys.stderr.write(
        "pyyaml is required (use DriverScript/.venv). pip install pyyaml\n"
    )
    sys.exit(1)

# Resolve paths relative to the repo root (this file lives at GT_esmini/scripts/).
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.normpath(os.path.join(_SCRIPT_DIR, "..", ".."))
_YAML = os.path.join(
    _REPO_ROOT, "GT_esmini", "test", "odr_fixtures", "parser_coverage.yaml"
)
_OUT = os.path.join(
    _REPO_ROOT, "GT_esmini", "src", "road", "odr_side", "OdrCoverageWhitelist.inc"
)


def _c_escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def main():
    with open(_YAML, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    elements = data.get("elements") or []
    rows = {}
    for e in elements:
        path = e["path"]
        attrs = e.get("attrs") or []
        # Deterministic, sorted attr order; dedupe defensively.
        attrs_sorted = sorted(set(attrs))
        if path in rows:
            raise SystemExit("duplicate path in parser_coverage.yaml: %s" % path)
        rows[path] = attrs_sorted

    # Sorted by path so the C++ side can std::lower_bound. Use plain byte/codepoint
    # ordering (Python default) -- the C++ comparator must match (std::string::operator<,
    # i.e. unsigned char lexicographic, which is byte order for ASCII paths).
    sorted_paths = sorted(rows.keys())

    total_attr_pairs = sum(len(rows[p]) for p in sorted_paths)

    lines = []
    lines.append("// GENERATED by gen_odr_whitelist.py -- do not hand-edit.")
    lines.append("// Source of truth: GT_esmini/test/odr_fixtures/parser_coverage.yaml")
    lines.append(
        "// Regenerate: DriverScript/.venv/Scripts/python.exe GT_esmini/scripts/gen_odr_whitelist.py"
    )
    lines.append(
        "// Plan: GT_esmini/docs/archive/odr_1619_program/opendrive_16_19_support_plan.md P1 (OdrCoverageAudit)."
    )
    lines.append("//")
    lines.append(
        "// Entries are sorted by 'path' (byte/codepoint order == std::string::operator<"
    )
    lines.append("// for ASCII), enabling std::lower_bound lookup. 'attrs_csv' is the")
    lines.append(
        "// comma-separated set of attributes the parser reads on that element; an empty"
    )
    lines.append(
        "// string means 'no attributes read' (container or attribute-less element)."
    )
    lines.append("//")
    lines.append(
        "// Counts: %d element paths, %d (path,attr) pairs."
        % (len(sorted_paths), total_attr_pairs)
    )
    lines.append("")
    lines.append("// clang-format off")
    lines.append("static const GtOdrWhitelistRow kGtOdrWhitelist[] = {")
    for p in sorted_paths:
        csv = ",".join(rows[p])
        lines.append('    {"%s", "%s"},' % (_c_escape(p), _c_escape(csv)))
    lines.append("};")
    lines.append("")
    lines.append(
        "static const size_t kGtOdrWhitelistCount = sizeof(kGtOdrWhitelist) / sizeof(kGtOdrWhitelist[0]);"
    )
    lines.append("// clang-format on")
    lines.append("")

    content = "\n".join(lines)

    os.makedirs(os.path.dirname(_OUT), exist_ok=True)
    with open(_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)

    print("wrote %s" % _OUT)
    print(
        "  %d element paths, %d (path,attr) pairs"
        % (len(sorted_paths), total_attr_pairs)
    )


if __name__ == "__main__":
    main()
