#!/usr/bin/env python3
"""P9b permanent double-processing guards (text side) -- plan §5 P9b resync deliverable.

After an upstream resync, the silent failure modes this guards against are:

  1. WHITELIST DRIFT: parser_coverage.yaml edited without regenerating
     OdrCoverageWhitelist.inc (the audit then enforces a stale contract).
     -> recompute the .inc content in-memory (same algorithm as
        gen_odr_whitelist.py) and require byte-equality with the committed file.

  2. DUAL ATTRIBUTION: the same element path claimed twice in
     parser_coverage.yaml (two entries competing for one path -- the generator
     also rejects this, but the guard reports it even when nobody regenerates).

  3. HANDLED-BY-UPSTREAM CONTRADICTION: after upstream natively adopts an
     element (e.g. a PR-VJ slice is merged upstream), the resync checklist
     re-baselines the entry with `handled_by_upstream: true` AND removes the
     GT-side processing. An entry flagged handled_by_upstream whose `evidence`
     still references a GT file (odr_side / GT_) is exactly the double-parse
     state the checklist forbids -> FAIL.

  4. SYNTH-ID FAMILY DRIFT: the three synthesis id bases (crosswalk 9.0e8 /
     bridge 9.1e8 / objectReference 9.2e8) must stay disjoint 10M ranges.
     Sourced from the odr_side sources themselves (grep), not a copy here.

The behavioral side (no duplicated RMObject ids, re-parse idempotence) lives in
GT_esmini/test/unit/road/test_OdrResyncGuards.cpp (unit ctest gate).

Importable: run_odr_conformance.py calls run_check() in EVERY profile (like
check_fork_drift / check_core_census), so the guard is permanently wired into
conformance quick/full and regression-gate Step 1.5.

Standalone: DriverScript/.venv/Scripts/python.exe scripts/check_resync_guards.py
Exit 0 iff all guards pass.
"""
from __future__ import annotations

import os
import re
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.normpath(os.path.join(_SCRIPT_DIR, ".."))
_YAML = os.path.join(_REPO_ROOT, "GT_esmini", "test", "odr_fixtures", "parser_coverage.yaml")
_INC = os.path.join(_REPO_ROOT, "GT_esmini", "src", "road", "odr_side", "OdrCoverageWhitelist.inc")
_ODR_SIDE = os.path.join(_REPO_ROOT, "GT_esmini", "src", "road", "odr_side")

_GT_EVIDENCE_RE = re.compile(r"odr_side|Odr[A-Z]\w*\.cpp|GT_esmini", re.IGNORECASE)
_SYNTH_BASE_RE = re.compile(
    r"constexpr\s+unsigned\s+int\s+k(\w+)SynthIdBase\s*=\s*(\d+)u?")

_FAMILY_SPAN = 10_000_000


def _load_yaml():
    import yaml  # deferred: standalone callers may lack pyyaml until venv is used

    with open(_YAML, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def _expected_inc_text(elements) -> str:
    """Recompute the whitelist .inc content -- MUST mirror gen_odr_whitelist.py."""
    rows = {}
    for e in elements:
        rows[e["path"]] = sorted(set(e.get("attrs") or []))
    sorted_paths = sorted(rows.keys())
    total_attr_pairs = sum(len(rows[p]) for p in sorted_paths)

    def esc(t):
        return t.replace("\\", "\\\\").replace('"', '\\"')

    lines = []
    lines.append("// GENERATED by gen_odr_whitelist.py -- do not hand-edit.")
    lines.append("// Source of truth: GT_esmini/test/odr_fixtures/parser_coverage.yaml")
    lines.append("// Regenerate: DriverScript/.venv/Scripts/python.exe GT_esmini/scripts/gen_odr_whitelist.py")
    lines.append("// Plan: GT_esmini/docs/archive/odr_1619_program/opendrive_16_19_support_plan.md P1 (OdrCoverageAudit).")
    lines.append("//")
    lines.append("// Entries are sorted by 'path' (byte/codepoint order == std::string::operator<")
    lines.append("// for ASCII), enabling std::lower_bound lookup. 'attrs_csv' is the")
    lines.append("// comma-separated set of attributes the parser reads on that element; an empty")
    lines.append("// string means 'no attributes read' (container or attribute-less element).")
    lines.append("//")
    lines.append("// Counts: %d element paths, %d (path,attr) pairs." % (len(sorted_paths), total_attr_pairs))
    lines.append("")
    lines.append("// clang-format off")
    lines.append("static const GtOdrWhitelistRow kGtOdrWhitelist[] = {")
    for p in sorted_paths:
        lines.append('    {"%s", "%s"},' % (esc(p), esc(",".join(rows[p]))))
    lines.append("};")
    lines.append("")
    lines.append("static const size_t kGtOdrWhitelistCount = sizeof(kGtOdrWhitelist) / sizeof(kGtOdrWhitelist[0]);")
    lines.append("// clang-format on")
    lines.append("")
    return "\n".join(lines)


def run_check(repo_root: str | None = None) -> dict:
    """Run all text-side guards. Returns {ok, failures: [str], summary: str}."""
    failures: list[str] = []

    data = _load_yaml()
    elements = data.get("elements") or []

    # Guard 2: dual attribution (duplicate paths).
    seen: set[str] = set()
    for e in elements:
        p = e.get("path", "")
        if p in seen:
            failures.append(f"duplicate parser_coverage path: {p}")
        seen.add(p)

    # Guard 3: handled-by-upstream contradiction.
    for e in elements:
        if e.get("handled_by_upstream") and _GT_EVIDENCE_RE.search(str(e.get("evidence", ""))):
            failures.append(
                f"handled_by_upstream entry still carries GT evidence (double-parse): {e['path']}"
            )

    # Guard 1: whitelist regen drift (byte-equality, LF-normalized -- the .inc may be
    # checked out with CRLF under core.autocrlf).
    try:
        with open(_INC, "r", encoding="utf-8", newline="") as f:
            committed = f.read().replace("\r\n", "\n")
        expected = _expected_inc_text(elements)
        if committed != expected:
            failures.append(
                "OdrCoverageWhitelist.inc is stale vs parser_coverage.yaml "
                "(regenerate: GT_esmini/scripts/gen_odr_whitelist.py)"
            )
    except OSError as exc:
        failures.append(f"cannot read OdrCoverageWhitelist.inc: {exc}")

    # Guard 4: synth-id family bases (read from the odr_side sources, not a copy).
    bases: dict[str, int] = {}
    for fn in os.listdir(_ODR_SIDE):
        if not fn.endswith(".cpp"):
            continue
        with open(os.path.join(_ODR_SIDE, fn), "r", encoding="utf-8", errors="replace") as f:
            for m in _SYNTH_BASE_RE.finditer(f.read()):
                bases[m.group(1)] = int(m.group(2))
    if len(bases) < 3:
        failures.append(f"expected >=3 synth-id base constants in odr_side, found {sorted(bases)}")
    else:
        vals = sorted(bases.values())
        for a, b in zip(vals, vals[1:]):
            if b - a < _FAMILY_SPAN:
                failures.append(f"synth-id family ranges overlap: {a} and {b} (< {_FAMILY_SPAN} apart)")

    ok = not failures
    summary = (
        f"resync-guards: OK ({len(elements)} whitelist entries, {len(bases)} synth families)"
        if ok
        else "resync-guards: FAIL (" + "; ".join(failures[:4]) + ")"
    )
    return {"ok": ok, "failures": failures, "summary": summary}


def main() -> int:
    res = run_check()
    print(res["summary"])
    for f in res["failures"]:
        print("  FAIL:", f)
    return 0 if res["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
