#!/usr/bin/env python3
"""LogicalLane connectivity probe (spine-work:osi-logical-lane S2, design 2-4).

What only a real run against real road networks can answer:

  1. REFERENCE CLOSURE. Every other_lane_id in predecessor_lane / successor_lane /
     left_adjacent_lane / right_adjacent_lane must name a LogicalLane that is
     actually in the message. A build that resolves an id through a stale index, or
     through a lane section that was skipped, produces a perfectly well-formed
     message full of dangling references.

  2. at_begin_of_other_lane IN BOTH POLARITIES, WHERE IT IS NOT STRUCTURAL. Inside
     one road the flag follows from which way you are looking (the next lane section
     is always entered at its beginning), so it is 50/50 whatever the code does and
     proves nothing. Only a connection that CROSSES a road boundary derives the flag
     from an OpenDRIVE @contactPoint. This counts the two polarities separately for
     cross-road connections, so a build that ignored contact points and always wrote
     `true` is visible.

  3. THE INSIDE OF AN INTERSECTION IS WALKABLE. The physical osi_lane fuses a whole
     junction into one TYPE_INTERSECTION lane; the logical layer keeps every
     connecting-road lane separate, which is the entire reason it exists. Reported as
     a census: of all lanes on roads with @junction set, how many have at least one
     predecessor AND at least one successor.

  4. ADJACENCY AGREES WITH THE BOUNDARIES (only checkable since S3). The proto: "The
     XY positions of the polyline generated by the LogicalLaneBoundaries of adjacent
     lanes must match up to a small error (5cm)." Two lanes that are neighbours
     usually share a boundary id, so this is 0 by construction -- but not where the
     curb exception split the edge by height, and THOSE are the pairs that can drift.
     Measured polyline-to-polyline in XY, with the shared and split populations
     reported separately so a run where only one occurred is visible as such.

  5. SYMMETRY. "A is right of B" must come back as "B is left of A", and a
     connection must be reachable from both ends. OpenDRIVE declares a junction
     meeting from one side only, so this is the property that says the mirror the
     post-pass emits actually landed.

  6. ORDERING. "Entries must be ordered: first by #start_s, then by #end_s", and
     LaneRelation requires end_s > start_s.

  7. FLAG OFF. GT_OSI_LOGICAL_LANE=0 -> no connectivity at all.

    DriverScript/.venv/Scripts/python.exe scripts/probe_osi_logical_lane_connectivity.py

Exit 0 = PASS. Requires a completed Release build (GT_esminiLib.dll, esminiRMLib.dll).
Output: test_results/osi_logical_lane/connectivity_probe.json (+ a table on stdout).
"""
import argparse
import json
import os
import subprocess
import sys
import tempfile

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_DLL = os.path.join(_REPO_ROOT, "build", "GT_esmini", "Release", "GT_esminiLib.dll")
DEFAULT_RM_DLL = os.path.join(_REPO_ROOT, "build", "GT_esmini", "Release", "esminiRMLib.dll")
OUT_DIR = os.path.join(_REPO_ROOT, "test_results", "osi_logical_lane")

ENV_FLAG = "GT_OSI_LOGICAL_LANE"

# The same five networks the size and boundary probes use.
#   e6mini              ONE road, ONE lane section -- the negative control: nothing to connect
#   fabriksgatan        small urban junction, 12 connecting roads, contact points both ways
#   multi_intersections 63 roads / 76 connecting-road lanes -- the stress case
#   soderleden          motorway with ramps
#   highway_merge_split lane sections that add and drop lanes (zero-width ends)
FIXTURES = [
    ("e6mini", "resources/xodr/e6mini.xodr"),
    ("fabriksgatan", "resources/xodr/fabriksgatan.xodr"),
    ("multi_intersections", "resources/xodr/multi_intersections.xodr"),
    ("soderleden", "resources/xodr/soderleden.xodr"),
    ("highway_merge_split", "resources/xodr/highway_example_with_merge_and_split.xodr"),
]

# osi_logicallane.proto, LogicalLane.left/right_adjacent_lane.
SPEC_ADJACENT_XY_M = 0.05


_WORKER = r'''
import sys, os, json, math, ctypes
import xml.etree.ElementTree as ET
REPO_ROOT = %(repo)r
sys.path.insert(0, os.path.join(REPO_ROOT, "scripts"))
sys.path.insert(0, os.path.join(REPO_ROOT, "GT_esmini", "scripts"))
sys.path.insert(0, os.path.join(REPO_ROOT, "GT_esmini", "scripts", "verification"))

out       = %(out)r
osi_file  = %(osi_file)r
fixtures  = %(fixtures)r
dll       = %(dll)r
rm_dll    = %(rm_dll)r

XOSC = """<?xml version="1.0"?>
<OpenSCENARIO>
  <FileHeader revMajor="1" revMinor="2" date="2026-09-24T00:00:00" description="connectivity probe" author="GT"/>
  <ParameterDeclarations/><CatalogLocations/>
  <RoadNetwork><LogicFile filepath="%%s"/></RoadNetwork>
  <Entities><ScenarioObject name="Ego"><Vehicle name="car" vehicleCategory="car">
    <ParameterDeclarations/>
    <Performance maxSpeed="60" maxDeceleration="10" maxAcceleration="5"/>
    <BoundingBox><Center x="1.4" y="0.0" z="0.75"/><Dimensions width="2.0" length="5.0" height="1.5"/></BoundingBox>
    <Axles><FrontAxle maxSteering="0.5" wheelDiameter="0.6" trackWidth="1.8" positionX="2.8" positionZ="0.3"/>
           <RearAxle maxSteering="0.0" wheelDiameter="0.6" trackWidth="1.8" positionX="0.0" positionZ="0.3"/></Axles>
    <Properties/></Vehicle></ScenarioObject></Entities>
  <Storyboard><Init><Actions><Private entityRef="Ego"><PrivateAction><TeleportAction><Position>
    <LanePosition roadId="%%s" laneId="%%s" offset="0" s="1.0"/>
  </Position></TeleportAction></PrivateAction></Private></Actions></Init>
  <Story name="s"><Act name="a"><ManeuverGroup maximumExecutionCount="1" name="m"><Actors selectTriggeringEntities="false"/></ManeuverGroup>
    <StartTrigger><ConditionGroup><Condition name="c" delay="0" conditionEdge="none">
      <ByValueCondition><SimulationTimeCondition value="0" rule="greaterThan"/></ByValueCondition></Condition></ConditionGroup></StartTrigger>
  </Act></Story>
  <StopTrigger><ConditionGroup><Condition name="stop" delay="0" conditionEdge="none">
    <ByValueCondition><SimulationTimeCondition value="1.0" rule="greaterThan"/></ByValueCondition></Condition></ConditionGroup></StopTrigger>
  </Storyboard>
</OpenSCENARIO>
"""


def max_xy_between(a_pts, b_pts):
    """Largest XY distance from any point of polyline A to polyline B.

    Point-to-segment, not point-to-point: the two boundaries are refined
    independently and need not carry the same number of points."""
    worst = 0.0
    for p in a_pts:
        best = None
        for k in range(1, len(b_pts)):
            ax, ay = b_pts[k - 1]
            bx, by = b_pts[k]
            dx, dy = bx - ax, by - ay
            den = dx * dx + dy * dy
            u = 0.0 if den <= 0.0 else ((p[0] - ax) * dx + (p[1] - ay) * dy) / den
            u = max(0.0, min(1.0, u))
            d = math.hypot(p[0] - (ax + u * dx), p[1] - (ay + u * dy))
            if best is None or d < best:
                best = d
        if best is not None and best > worst:
            worst = best
    return worst


res = {"fixtures": [], "error": None}
try:
    import osi3.osi_groundtruth_pb2 as gtpb
    from gt_lib import GtLib
    from rm_lib import EsminiRMLib

    gt = GtLib(dll_path=dll)

    for fx_idx, (label, xodr) in enumerate(fixtures):
        r = {"label": label, "xodr": xodr, "init_rc": None, "error": None,
             "logical_lanes": 0,
             "pred": 0, "succ": 0, "left": 0, "right": 0,
             "dangling": 0, "dangling_examples": [],
             # polarity, split by whether the flag could have come from a contact point
             "same_road_at_begin": [0, 0], "cross_road_at_begin": [0, 0],
             "junction_edge_at_begin": [0, 0],
             # junction census
             "connecting_lanes": 0, "connecting_with_pred": 0, "connecting_with_succ": 0,
             "connecting_missing": [],
             # adjacency vs boundaries
             "adj_pairs": 0, "adj_shared_id": 0, "adj_split": 0, "adj_max_xy": 0.0,
             "adj_bad": [], "adj_no_boundary": 0, "adj_split_examples": [],
             "adj_control_xy": 0.0, "adj_control_pairs": 0,
             # symmetry / ordering / ranges
             "adj_asymmetric": [], "conn_asymmetric": [], "conn_meetings": 0,
             "order_bad": [], "range_bad": [],
             "contradictory_at_begin": [], "both_pred_and_succ": 0,
             "lanes_without_any_connection": 0}

        rm = None
        try:
            rm = EsminiRMLib(rm_dll)
            r["rm_init_rc"] = rm.Init(os.path.join(REPO_ROOT, xodr))
        except Exception as exc:                      # noqa: BLE001
            r["error"] = "rm init failed: %%s" %% exc
            res["fixtures"].append(r)
            continue
        if r["rm_init_rc"] != 0:
            r["error"] = "RM_Init rc=%%s" %% r["rm_init_rc"]
            res["fixtures"].append(r)
            continue

        entry_road, entry_lane = None, None
        for ri in range(rm.GetNumberOfRoads()):
            rid = rm.GetIdOfRoadFromIndex(ri)
            for li in range(rm.GetRoadNumberOfDrivableLanes(rid, 1.0)):
                lrc, lid = rm.GetDrivableLaneIdByIndex(rid, li, 1.0)
                if lrc == 0 and lid < 0:
                    entry_road, entry_lane = rid, lid
                    break
            if entry_road is not None:
                break
        rm.Close()
        if entry_road is None:
            r["error"] = "no drivable lane found"
            res["fixtures"].append(r)
            continue

        # Which roads are connecting roads, read from the FILE rather than from the
        # message under test: the census below has to be anchored to something the
        # post-pass did not produce.
        junction_of = {}
        opportunities = 0
        for road in ET.parse(os.path.join(REPO_ROOT, xodr)).getroot().findall("road"):
            try:
                junction_of[int(road.get("id"))] = int(road.get("junction", "-1"))
            except (TypeError, ValueError):
                pass
            # Places where the FILE says two lane ends meet: every lane-section seam
            # and every road-level <link>. A network with none of them (e6mini: one
            # road, one lane section) must come out with zero connections, and a
            # build that invented some has to fail rather than be excused.
            opportunities += max(0, len(road.findall("lanes/laneSection")) - 1)
            link = road.find("link")
            if link is not None:
                opportunities += len(link.findall("predecessor")) + len(link.findall("successor"))
        r["connecting_roads_in_file"] = sum(1 for v in junction_of.values() if v != -1)
        r["meeting_opportunities_in_file"] = opportunities

        xosc_path = os.path.join(os.path.dirname(out), "gt_ll_conn_%%d.xosc" %% fx_idx)
        with open(xosc_path, "w") as fh:
            fh.write(XOSC %% (os.path.join(REPO_ROOT, xodr).replace("\\", "/"), entry_road, entry_lane))

        rc = gt.init_with_args(["--osc", xosc_path, "--headless", "--fixed_timestep", "0.05", "--disable_stdout"])
        r["init_rc"] = rc
        if rc != 0:
            res["fixtures"].append(r)
            continue
        gt.set_osi_frequency(1)
        this_osi = osi_file + ".%%d" %% fx_idx
        gt.lib.SE_EnableOSIFile(this_osi.encode("utf-8"))
        gt.step(0.05)
        gt.lib.SE_FlushOSIFile()

        g = gtpb.GroundTruth()
        with open(this_osi, "rb") as fh:
            raw = fh.read()
        rec_len = int.from_bytes(raw[0:4], "little")
        g.ParseFromString(raw[4:4 + rec_len])
        r["static_record_bytes"] = rec_len
        r["logical_lanes"] = len(g.logical_lane)

        ids = {ll.id.value for ll in g.logical_lane}
        by_id = {ll.id.value: ll for ll in g.logical_lane}
        bnd_xy = {}
        for b in g.logical_lane_boundary:
            bnd_xy[b.id.value] = [(p.position.x, p.position.y) for p in b.boundary_line]

        # OpenDRIVE address of each logical lane, from its source_reference.
        addr = {}
        for ll in g.logical_lane:
            road_id, lane_id = None, None
            for sr in ll.source_reference:
                for ident in sr.identifier:
                    if ident.startswith("road_id:"):
                        road_id = int(ident.split(":", 1)[1])
                    elif ident.startswith("lane_id:"):
                        lane_id = int(ident.split(":", 1)[1])
            addr[ll.id.value] = (road_id, lane_id)

        def note_dangling(kind, src, other):
            r["dangling"] += 1
            if len(r["dangling_examples"]) < 5:
                r["dangling_examples"].append([kind, addr.get(src), other])

        for ll in g.logical_lane:
            my_road = addr.get(ll.id.value, (None, None))[0]
            n_here = 0
            for kind, lst in (("pred", ll.predecessor_lane), ("succ", ll.successor_lane)):
                # TWO INDEPENDENT DERIVATIONS OF at_begin MEET HERE. A road boundary
                # inside a junction is resolved both from the connecting road's own
                # @contactPoint and from the junction's <connection> @contactPoint.
                # They are deduplicated on (id, at_begin), so if the two disagreed the
                # SAME other lane would appear twice in this list with opposite flags.
                # That is the only way the disagreement is visible at all -- counts
                # alone would look healthy.
                seen_here = {}
                for c in lst:
                    prev_flag = seen_here.get(c.other_lane_id.value)
                    if prev_flag is not None and prev_flag != c.at_begin_of_other_lane:
                        if len(r["contradictory_at_begin"]) < 10:
                            r["contradictory_at_begin"].append([addr.get(ll.id.value), kind,
                                                                addr.get(c.other_lane_id.value)])
                    seen_here[c.other_lane_id.value] = c.at_begin_of_other_lane
                    r[kind] += 1
                    n_here += 1
                    if c.other_lane_id.value not in ids:
                        note_dangling(kind, ll.id.value, c.other_lane_id.value)
                        continue
                    other_road = addr.get(c.other_lane_id.value, (None, None))[0]
                    bucket = "same_road_at_begin" if other_road == my_road else "cross_road_at_begin"
                    r[bucket][1 if c.at_begin_of_other_lane else 0] += 1
                    if junction_of.get(my_road, -1) != -1 or junction_of.get(other_road, -1) != -1:
                        r["junction_edge_at_begin"][1 if c.at_begin_of_other_lane else 0] += 1
            for kind, lst in (("left", ll.left_adjacent_lane), ("right", ll.right_adjacent_lane)):
                prev = None
                for rel in lst:
                    r[kind] += 1
                    n_here += 1
                    if rel.other_lane_id.value not in ids:
                        note_dangling(kind, ll.id.value, rel.other_lane_id.value)
                    if not (rel.end_s > rel.start_s):
                        r["range_bad"].append([addr.get(ll.id.value), kind, rel.start_s, rel.end_s])
                    key = (rel.start_s, rel.end_s)
                    if prev is not None and key < prev:
                        r["order_bad"].append([addr.get(ll.id.value), kind, prev, key])
                    prev = key
            both = {x.other_lane_id.value for x in ll.predecessor_lane} &                    {x.other_lane_id.value for x in ll.successor_lane}
            r["both_pred_and_succ"] += len(both)
            if n_here == 0:
                r["lanes_without_any_connection"] += 1

        # 3. Junction census -- from the file's own notion of a connecting road.
        for ll in g.logical_lane:
            road_id = addr.get(ll.id.value, (None, None))[0]
            if junction_of.get(road_id, -1) == -1:
                continue
            r["connecting_lanes"] += 1
            has_p = len(ll.predecessor_lane) > 0
            has_s = len(ll.successor_lane) > 0
            r["connecting_with_pred"] += 1 if has_p else 0
            r["connecting_with_succ"] += 1 if has_s else 0
            if not (has_p and has_s) and len(r["connecting_missing"]) < 10:
                r["connecting_missing"].append([addr.get(ll.id.value), len(ll.predecessor_lane),
                                                len(ll.successor_lane)])

        # 4 + 5. Adjacency: symmetric, and agreeing with the boundaries.
        for ll in g.logical_lane:
            for side, lst in (("right", ll.right_adjacent_lane), ("left", ll.left_adjacent_lane)):
                for rel in lst:
                    other = by_id.get(rel.other_lane_id.value)
                    if other is None:
                        continue
                    back = other.left_adjacent_lane if side == "right" else other.right_adjacent_lane
                    if ll.id.value not in [x.other_lane_id.value for x in back]:
                        if len(r["adj_asymmetric"]) < 10:
                            r["adj_asymmetric"].append([addr.get(ll.id.value), side,
                                                        addr.get(rel.other_lane_id.value)])
                    if side != "right":
                        continue  # measure each pair once, from the right-hand side
                    mine = [i.value for i in ll.right_boundary_id]
                    theirs = [i.value for i in other.left_boundary_id]
                    r["adj_pairs"] += 1
                    if mine and mine == theirs:
                        r["adj_shared_id"] += 1
                        continue
                    a_pts = [p for bid in mine for p in bnd_xy.get(bid, [])]
                    b_pts = [p for bid in theirs for p in bnd_xy.get(bid, [])]
                    if len(a_pts) < 2 or len(b_pts) < 2:
                        r["adj_no_boundary"] += 1
                        continue
                    r["adj_split"] += 1
                    d = max(max_xy_between(a_pts, b_pts), max_xy_between(b_pts, a_pts))
                    r["adj_max_xy"] = max(r["adj_max_xy"], d)
                    if len(r["adj_split_examples"]) < 5:
                        r["adj_split_examples"].append([addr.get(ll.id.value),
                                                        addr.get(rel.other_lane_id.value), round(d, 6)])
                    if d > %(spec_xy)f:
                        if len(r["adj_bad"]) < 10:
                            r["adj_bad"].append([addr.get(ll.id.value),
                                                 addr.get(rel.other_lane_id.value), round(d, 6)])

        # NEGATIVE CONTROL for the measurement above. Every adjacent pair comes out at
        # 0 -- shared ids trivially, height-split ones because the split copies the XY
        # of one edge -- so the number alone cannot say whether max_xy_between() is
        # able to report anything at all. This runs the SAME function on a pair it
        # must reject: this lane's RIGHT boundary against the LEFT neighbour's LEFT
        # boundary, which are two different edges a lane width apart. If this is also
        # 0, the 5cm check above is measuring nothing.
        for ll in g.logical_lane:
            if not ll.right_adjacent_lane or not ll.left_adjacent_lane:
                continue
            far = by_id.get(ll.left_adjacent_lane[0].other_lane_id.value)
            if far is None:
                continue
            a_pts = [p for bid in ll.right_boundary_id for p in bnd_xy.get(bid.value, [])]
            b_pts = [p for bid in far.left_boundary_id for p in bnd_xy.get(bid.value, [])]
            if len(a_pts) < 2 or len(b_pts) < 2:
                continue
            r["adj_control_pairs"] += 1
            r["adj_control_xy"] = max(r["adj_control_xy"],
                                      max_xy_between(a_pts, b_pts), max_xy_between(b_pts, a_pts))

        # 5b. Connections reachable from both ends. A meeting recorded as A.succ -> B
        #     must appear on B as either a pred or a succ naming A; which of the two
        #     depends on which of B's ends it is, so both are accepted here.
        for ll in g.logical_lane:
            for kind, lst in (("pred", ll.predecessor_lane), ("succ", ll.successor_lane)):
                for c in lst:
                    other = by_id.get(c.other_lane_id.value)
                    if other is None:
                        continue
                    r["conn_meetings"] += 1
                    back = [x.other_lane_id.value for x in other.predecessor_lane] + \
                           [x.other_lane_id.value for x in other.successor_lane]
                    if ll.id.value not in back and len(r["conn_asymmetric"]) < 10:
                        r["conn_asymmetric"].append([addr.get(ll.id.value), kind,
                                                     addr.get(c.other_lane_id.value)])

        gt.close()
        res["fixtures"].append(r)
except Exception as exc:                              # noqa: BLE001
    import traceback
    res["error"] = traceback.format_exc()

with open(out, "w") as fh:
    json.dump(res, fh)
'''


def _run_worker(dll, rm_dll, fixtures, flag_on):
    """One subprocess per polarity, so the GT_OSI_LOGICAL_LANE latch is fresh."""
    out_fd, out_path = tempfile.mkstemp(suffix=".json")
    os.close(out_fd)
    src = _WORKER % {
        "repo": _REPO_ROOT,
        "out": out_path,
        "osi_file": os.path.join(tempfile.gettempdir(), "gt_ll_conn_probe.osi"),
        "fixtures": fixtures,
        "dll": dll,
        "rm_dll": rm_dll,
        "spec_xy": SPEC_ADJACENT_XY_M,
    }
    py_fd, py_path = tempfile.mkstemp(suffix=".py")
    with os.fdopen(py_fd, "w") as fh:
        fh.write(src)

    # The two polarities are "unset" and "0", NOT "1" and "unset": the variable has
    # been an OPT-OUT since S3, so leaving it unset is what exercises the default and
    # setting it to 0 is what exercises the escape hatch. Written the other way round
    # both runs would come out ON and every OFF assertion would pass vacuously.
    env = dict(os.environ)
    if flag_on:
        env.pop(ENV_FLAG, None)
    else:
        env[ENV_FLAG] = "0"

    proc = subprocess.run([sys.executable, py_path], env=env, capture_output=True, text=True,
                          cwd=_REPO_ROOT, timeout=3600)
    try:
        with open(out_path) as fh:
            result = json.load(fh)
    except Exception:  # noqa: BLE001
        result = {"fixtures": [], "error": "worker produced no JSON\n%s\n%s"
                  % (proc.stdout[-4000:], proc.stderr[-4000:])}
    result["worker_rc"] = proc.returncode
    for path in (out_path, py_path):
        try:
            os.unlink(path)
        except OSError:
            pass
    return result


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dll", default=DEFAULT_DLL)
    ap.add_argument("--rm-dll", default=DEFAULT_RM_DLL)
    args = ap.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)
    for path in (args.dll, args.rm_dll):
        if not os.path.exists(path):
            print("FAIL: no library at %s -- build Release first" % path)
            return 1

    failures = []
    report = {"dll": args.dll, "rm_dll": args.rm_dll}

    def check(name, ok, detail=""):
        print("  [%s] %s%s" % ("PASS" if ok else "FAIL", name, (" -- " + detail) if detail else ""))
        if not ok:
            failures.append("%s: %s" % (name, detail))

    fixtures = [[label, xodr] for (label, xodr) in FIXTURES]

    print("== GT_OSI_LOGICAL_LANE unset (default ON) ==")
    on = _run_worker(args.dll, args.rm_dll, fixtures, True)
    report["on"] = on
    if on.get("error"):
        check("worker_on", False, on["error"][-2000:])
        _write(report)
        return 1

    totals = {"cross_false": 0, "cross_true": 0, "junction_false": 0, "junction_true": 0,
              "adj_shared": 0, "adj_split": 0, "connecting_lanes": 0, "connecting_both": 0,
              "adj_control_xy": 0.0, "adj_control_pairs": 0}
    for r in on["fixtures"]:
        label = r["label"]
        print("  -- %s" % label)
        if r.get("error") or r["init_rc"] != 0:
            check("%s.init" % label, False, "%s (init rc=%s)" % (r.get("error"), r["init_rc"]))
            continue
        want_connections = r.get("meeting_opportunities_in_file", 0) > 0
        check("%s.connectivity_matches_the_file" % label,
              ((r["pred"] + r["succ"]) > 0) == want_connections,
              "%d predecessor / %d successor / %d left / %d right over %d logical lanes; the xodr "
              "offers %d lane-end meeting opportunit(y|ies), so connections are %s"
              % (r["pred"], r["succ"], r["left"], r["right"], r["logical_lanes"],
                 r.get("meeting_opportunities_in_file", -1),
                 "expected" if want_connections else "expected to be ABSENT"))
        check("%s.reference_closure" % label, r["dangling"] == 0,
              "%d/%d references resolve in logical_lane[]%s"
              % (r["pred"] + r["succ"] + r["left"] + r["right"] - r["dangling"],
                 r["pred"] + r["succ"] + r["left"] + r["right"],
                 ("; first dangling: %s" % r["dangling_examples"][0]) if r["dangling_examples"] else ""))
        check("%s.relation_ordering" % label, not r["order_bad"] and not r["range_bad"],
              "%d out-of-order, %d with end_s <= start_s" % (len(r["order_bad"]), len(r["range_bad"])))
        check("%s.contact_point_derivations_agree" % label, not r["contradictory_at_begin"],
              "%d lane(s) named twice with opposite at_begin (%d named as both predecessor and "
              "successor, which is legal)%s"
              % (len(r["contradictory_at_begin"]), r["both_pred_and_succ"],
                 ("; first: %s" % r["contradictory_at_begin"][0]) if r["contradictory_at_begin"] else ""))
        check("%s.adjacency_symmetric" % label, not r["adj_asymmetric"],
              "%d one-sided adjacency relation(s)%s"
              % (len(r["adj_asymmetric"]),
                 ("; first: %s" % r["adj_asymmetric"][0]) if r["adj_asymmetric"] else ""))
        check("%s.connections_reachable_from_both_ends" % label, not r["conn_asymmetric"],
              "%d connection entries, %d not mirrored%s"
              % (r["conn_meetings"], len(r["conn_asymmetric"]),
                 ("; first: %s" % r["conn_asymmetric"][0]) if r["conn_asymmetric"] else ""))
        check("%s.adjacent_boundaries_within_5cm" % label,
              not r["adj_bad"],
              "%d neighbour pairs: %d share a boundary id (0 by construction), %d split by height "
              "-- max XY %.4f m (spec %.2f), %d without boundaries%s"
              % (r["adj_pairs"], r["adj_shared_id"], r["adj_split"], r["adj_max_xy"],
                 SPEC_ADJACENT_XY_M, r["adj_no_boundary"],
                 ("; first bad: %s" % r["adj_bad"][0]) if r["adj_bad"] else ""))
        if r["connecting_lanes"]:
            check("%s.connecting_road_lanes_linked" % label,
                  r["connecting_with_pred"] == r["connecting_lanes"]
                  and r["connecting_with_succ"] == r["connecting_lanes"],
                  "%d connecting-road lanes (%d connecting roads in the file): %d with a predecessor, "
                  "%d with a successor%s"
                  % (r["connecting_lanes"], r.get("connecting_roads_in_file", -1),
                     r["connecting_with_pred"], r["connecting_with_succ"],
                     ("; missing: %s" % r["connecting_missing"][:3]) if r["connecting_missing"] else ""))
        print("       at_begin_of_other_lane [false, true]: same-road %s / cross-road %s / junction-touching %s"
              % (r["same_road_at_begin"], r["cross_road_at_begin"], r["junction_edge_at_begin"]))
        totals["cross_false"] += r["cross_road_at_begin"][0]
        totals["cross_true"] += r["cross_road_at_begin"][1]
        totals["junction_false"] += r["junction_edge_at_begin"][0]
        totals["junction_true"] += r["junction_edge_at_begin"][1]
        totals["adj_control_xy"] = max(totals.get("adj_control_xy", 0.0), r["adj_control_xy"])
        totals["adj_control_pairs"] += r["adj_control_pairs"]
        totals["adj_shared"] += r["adj_shared_id"]
        totals["adj_split"] += r["adj_split"]
        totals["connecting_lanes"] += r["connecting_lanes"]
        totals["connecting_both"] += min(r["connecting_with_pred"], r["connecting_with_succ"])

    report["totals"] = totals
    # The discriminating one. Inside a road the flag is structural; only a connection
    # that crosses a road boundary reads an OpenDRIVE @contactPoint, so a build that
    # never looked at one shows up here as a single polarity.
    check("at_begin_both_polarities_across_roads",
          totals["cross_true"] > 0 and totals["cross_false"] > 0,
          "cross-road connections: %d with at_begin=true, %d with at_begin=false"
          % (totals["cross_true"], totals["cross_false"]))
    check("at_begin_both_polarities_at_junctions",
          totals["junction_true"] > 0 and totals["junction_false"] > 0,
          "connections touching a connecting road: %d true, %d false"
          % (totals["junction_true"], totals["junction_false"]))
    # Both branches of the adjacency/boundary rule have to occur, or the 5cm check
    # only ever ran on pairs where it is 0 by construction.
    # Every adjacent pair measures 0 m, which is the right answer and also what a
    # dead instrument returns. This is the same function on a pair it must reject.
    check("adjacency_measurement_can_report_a_violation",
          totals["adj_control_xy"] > SPEC_ADJACENT_XY_M,
          "the same polyline comparison, run on %d deliberately WRONG pairs (this lane's right "
          "boundary vs the left neighbour's left boundary), reports up to %.3f m -- well past the "
          "%.2f m the check would fail at" % (totals["adj_control_pairs"], totals["adj_control_xy"],
                                              SPEC_ADJACENT_XY_M))
    check("adjacency_split_population_present", totals["adj_split"] > 0,
          "%d neighbour pairs share a boundary id, %d are split by height and therefore "
          "actually measured against the 5cm rule" % (totals["adj_shared"], totals["adj_split"]))

    print("== GT_OSI_LOGICAL_LANE=0 ==")
    off = _run_worker(args.dll, args.rm_dll, fixtures, False)
    report["off"] = off
    if off.get("error"):
        check("worker_off", False, off["error"][-2000:])
    else:
        for r in off["fixtures"]:
            check("%s.no_connectivity_when_off" % r["label"],
                  r["logical_lanes"] == 0 and (r["pred"] + r["succ"] + r["left"] + r["right"]) == 0,
                  "logical_lane[] = %d, connections = %d"
                  % (r["logical_lanes"], r["pred"] + r["succ"] + r["left"] + r["right"]))
        # The OFF run has to be non-vacuous in the other direction too: if it had
        # silently run with the feature ON, the counts above would have been non-zero.
        check("off_run_is_the_other_polarity",
              any(x["logical_lanes"] == 0 for x in off["fixtures"])
              and any(x["logical_lanes"] > 0 for x in on["fixtures"]),
              "ON produced logical lanes and OFF produced none")

    _write(report)
    print()
    if failures:
        print("FAIL (%d):" % len(failures))
        for f in failures:
            print("  - " + f)
        return 1
    print("PASS -- report: %s" % os.path.join(OUT_DIR, "connectivity_probe.json"))
    return 0


def _write(report):
    with open(os.path.join(OUT_DIR, "connectivity_probe.json"), "w") as fh:
        json.dump(report, fh, indent=1)


if __name__ == "__main__":
    sys.exit(main())
