#!/usr/bin/env python3
"""strip_gt_markers.py -- remove [GT_ODR:...] provenance markers from source files.

The GT_esmini fork annotates every 2nd-class in-place core edit with
``[GT_ODR:<id>]`` marker comments (block form ``[GT_ODR:<id>-begin]`` /
``[GT_ODR:<id>-end]`` for larger hunks, ``:interp`` suffix on interpretation
points). The pristine copies carry these markers permanently so the census
tooling can attribute every hunk. Upstream PR branches, however, must be
free of any GT provenance -- they are generated by stripping the markers.

This script performs two kinds of edit, both idempotent:

  1. A line whose ONLY non-whitespace content is a marker comment
     (``// [GT_ODR:...]`` or ``# [GT_ODR:...]``) is deleted entirely.
     This covers block begin/end lines and standalone marker comments.

  2. A code line that ends in a trailing marker comment
     (``<code>  // [GT_ODR:...]`` / ``<code>  # [GT_ODR:...]``) keeps the
     code but drops the trailing comment (and the whitespace before it).

Nothing else is touched: the code is byte-identical apart from the marker
comments, so applying it twice is a no-op.

Usage:
    strip_gt_markers.py FILE [FILE ...]        # strip markers in place
    strip_gt_markers.py --check FILE [FILE...]  # verify zero markers remain (exit 1 if any)
    strip_gt_markers.py --selftest              # run inline unit tests
"""
import argparse
import re
import sys
import time

# A marker token: [GT_ODR:some-id], optionally -begin/-end, optionally :interp.
_MARKER_TOKEN = r"\[GT_ODR:[A-Za-z0-9:_-]+\]"

# A line that is nothing but leading whitespace + a marker comment.
# Comment introducer is // (C/C++) or # (python/cmake/yaml/shell).
_MARKER_ONLY_LINE = re.compile(
    r"^\s*(?://|#)\s*" + _MARKER_TOKEN + r".*$"
)

# A trailing marker comment on a code line: capture the code before it.
# Requires at least one non-comment character before the comment introducer.
_TRAILING_MARKER = re.compile(
    r"^(.*\S)\s*(?://|#)\s*" + _MARKER_TOKEN + r".*$"
)

# Bare detector (for --check): does the line reference a marker at all?
_ANY_MARKER = re.compile(_MARKER_TOKEN)


def strip_text(text):
    """Return (stripped_text, n_lines_removed, n_lines_trimmed)."""
    # Preserve the file's line ending. Detect CRLF vs LF from the first newline.
    crlf = "\r\n" in text
    # Split keeping content; we normalise on \n internally and re-emit.
    had_trailing_newline = text.endswith("\n")
    lines = text.split("\n")
    # If CRLF, each element still ends with \r; strip it and re-add on emit.
    out = []
    removed = 0
    trimmed = 0
    for raw in lines:
        line = raw[:-1] if (crlf and raw.endswith("\r")) else raw
        if _MARKER_ONLY_LINE.match(line):
            removed += 1
            continue
        m = _TRAILING_MARKER.match(line)
        if m:
            line = m.group(1).rstrip()
            trimmed += 1
        out.append(line)
    newline = "\r\n" if crlf else "\n"
    result = newline.join(out)
    if had_trailing_newline and not result.endswith(newline):
        # split() dropped the final empty element for a trailing newline; restore it
        result += newline
    return result, removed, trimmed


def count_markers(text):
    return sum(1 for line in text.splitlines() if _ANY_MARKER.search(line))


def process_file(path, check):
    with open(path, "r", encoding="utf-8", newline="") as fh:
        text = fh.read()
    if check:
        n = count_markers(text)
        if n:
            print(f"[FAIL] {path}: {n} marker line(s) remain", file=sys.stderr)
        return n
    stripped, removed, trimmed = strip_text(text)
    if stripped != text:
        # Windows editors/indexers can hold a transient lock right after a
        # branch checkout; retry a few times before giving up.
        for attempt in range(6):
            try:
                with open(path, "w", encoding="utf-8", newline="") as fh:
                    fh.write(stripped)
                break
            except PermissionError:
                if attempt == 5:
                    raise
                time.sleep(0.5)
    print(f"[strip] {path}: removed {removed} marker line(s), trimmed {trimmed} trailing marker(s)")
    return 0


def selftest():
    cases = []

    def check(name, cond):
        cases.append((name, cond))

    # 1. Standalone C++ marker-only line is removed.
    src = "int a = 1;\n    // [GT_ODR:vj-move-begin] window scan\ncode();\n    // [GT_ODR:vj-move-end]\nint b = 2;\n"
    out, rm, tr = strip_text(src)
    check("block markers removed", out == "int a = 1;\ncode();\nint b = 2;\n")
    check("block removed count", rm == 2 and tr == 0)

    # 2. Trailing marker comment: code kept, comment dropped.
    src = "    junction_type = VIRTUAL;  // [GT_ODR:vj-parse-junction] native\n"
    out, rm, tr = strip_text(src)
    check("trailing kept code", out == "    junction_type = VIRTUAL;\n")
    check("trailing counts", rm == 0 and tr == 1)

    # 3. :interp suffix handled.
    src = "    return -1;  // [GT_ODR:vj-membership:interp] v1 span reports -1\n"
    out, _, _ = strip_text(src)
    check("interp trailing stripped", out == "    return -1;\n")

    src = "    // [GT_ODR:vj-membership:interp] pinning comment only\nkeep;\n"
    out, rm, _ = strip_text(src)
    check("interp only-line removed", out == "keep;\n" and rm == 1)

    # 4. Python/# comment forms.
    src = "x = 1  # [GT_ODR:foo]\n# [GT_ODR:bar]\ny = 2\n"
    out, rm, tr = strip_text(src)
    check("hash forms", out == "x = 1\ny = 2\n" and rm == 1 and tr == 1)

    # 5. Idempotent: stripping twice == stripping once.
    src = "a;  // [GT_ODR:x]\n// [GT_ODR:y-begin]\nb;\n// [GT_ODR:y-end]\n"
    once, _, _ = strip_text(src)
    twice, rm2, tr2 = strip_text(once)
    check("idempotent", once == twice and rm2 == 0 and tr2 == 0)

    # 6. Non-marker comment is untouched.
    src = "int x;  // normal comment\n// another normal comment\n"
    out, rm, tr = strip_text(src)
    check("normal comments untouched", out == src and rm == 0 and tr == 0)

    # 7. count_markers matches.
    src = "a;  // [GT_ODR:x]\nplain\n// [GT_ODR:y-end]\n"
    check("count_markers", count_markers(src) == 2)
    stripped, _, _ = strip_text(src)
    check("count zero after strip", count_markers(stripped) == 0)

    # 8. CRLF preserved.
    src = "a;\r\n    // [GT_ODR:z]\r\nb;\r\n"
    out, rm, _ = strip_text(src)
    check("crlf preserved", out == "a;\r\nb;\r\n" and rm == 1)

    # 9. A marker mid-comment that is NOT a trailing comment on code stays a
    #    marker-only removal only if the line is solely the comment. A line that
    #    is code + non-marker // + then text is left alone (no false positive).
    src = "url = 'http://x';  // real url comment\n"
    out, rm, tr = strip_text(src)
    check("no false positive on //", out == src and rm == 0 and tr == 0)

    passed = sum(1 for _, c in cases if c)
    for name, cond in cases:
        print(f"  [{'PASS' if cond else 'FAIL'}] {name}")
    print(f"strip_gt_markers selftest: {passed}/{len(cases)} passed")
    return 0 if passed == len(cases) else 1


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("files", nargs="*", help="source files to strip / check")
    ap.add_argument("--check", action="store_true", help="verify zero markers remain (non-zero exit if any)")
    ap.add_argument("--selftest", action="store_true", help="run inline unit tests and exit")
    args = ap.parse_args(argv)

    if args.selftest:
        return selftest()
    if not args.files:
        ap.error("no files given (use --selftest for the unit tests)")

    if args.check:
        total = sum(process_file(p, check=True) for p in args.files)
        if total:
            print(f"strip_gt_markers --check: {total} marker line(s) across {len(args.files)} file(s)", file=sys.stderr)
            return 1
        print(f"strip_gt_markers --check: clean ({len(args.files)} file(s))")
        return 0

    for p in args.files:
        process_file(p, check=False)
    return 0


if __name__ == "__main__":
    sys.exit(main())
