# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from osi3 import osi_hostvehicledata_pb2 as osi3_dot_osi__hostvehicledata__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_hostvehicledata_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HostVehicleDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamHostVehicleData = channel.unary_stream(
                '/osi.server.HostVehicleDataService/StreamHostVehicleData',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=osi3_dot_osi__hostvehicledata__pb2.HostVehicleData.FromString,
                _registered_method=True)


class HostVehicleDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamHostVehicleData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostVehicleDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamHostVehicleData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamHostVehicleData,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=osi3_dot_osi__hostvehicledata__pb2.HostVehicleData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'osi.server.HostVehicleDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('osi.server.HostVehicleDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HostVehicleDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamHostVehicleData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/osi.server.HostVehicleDataService/StreamHostVehicleData',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            osi3_dot_osi__hostvehicledata__pb2.HostVehicleData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
