#!/usr/bin/env python
"""build_manifest.py — emit a gt_sim_test batch manifest from the generated catalog.

Globs scenario_templates/generated/*.xosc + their *.meta.yaml and writes
scenario_templates/generated/catalog_batch.yaml in EXACTLY the phase3_batch.yaml
format that gt_sim_test.batch() consumes:

    name: scenario_authoring_catalog
    defaults: {dt, max_time, snapshots, osi}
    scenarios:
      - scenario: <repo-relative posix path>
        policies: <from meta `policies:` key, default []>

No expectations / baseline are emitted — every layer-1 scenario is evaluated by
human annotation (evaluation: annotation), so the batch produces telemetry +
snapshots with verdict null/absent (frames > 0 is the only machine signal).

Ordering is deterministic (sorted by catalog_id). The manifest IS committed.

Regenerate with:
    DriverScript/.venv/Scripts/python.exe \
        resources/scenario_authoring/scenario_templates/build_manifest.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

# Make resources/scenario_authoring/ importable as the authoring package root.
_AUTHORING_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_AUTHORING_ROOT))

from authoring_common import repo_root  # noqa: E402

_GEN = Path(__file__).resolve().parent / "generated"
_MANIFEST = _GEN / "catalog_batch.yaml"
_REPO = repo_root()

# Batch defaults — mirror phase3_batch.yaml; max_time 40 so the 35 s stop trigger
# always fires within the cap. osi true so annotators get the captured scene.
_DEFAULTS = {"dt": 0.05, "max_time": 40.0, "snapshots": 3, "osi": True}

_HEADER = (
    "# scenario_authoring catalog batch manifest.\n"
    "# GENERATED by build_manifest.py — DO NOT HAND-EDIT.\n"
    "# Regenerate:\n"
    "#   DriverScript/.venv/Scripts/python.exe \\\n"
    "#       resources/scenario_authoring/scenario_templates/build_manifest.py\n"
    "#\n"
    "# Format = the phase3_batch.yaml schema consumed by gt_sim_test.batch().\n"
    "# evaluation is annotation (human), so NO expectations/baseline are emitted:\n"
    "# the batch yields telemetry + snapshots; verdict is null/absent by design.\n"
)


def _repo_rel_posix(p: Path) -> str:
    """Return *p* relative to the repo root using forward slashes."""
    return p.resolve().relative_to(_REPO).as_posix()


def build() -> dict:
    scenarios: list[dict] = []
    # Exclude esmini sanitizer droppings (*.temp.xosc) — they also end in .xosc.
    candidates = (p for p in _GEN.glob("*.xosc") if not p.name.endswith(".temp.xosc"))
    for xosc_path in sorted(candidates, key=lambda p: p.stem):
        meta_path = _GEN / f"{xosc_path.stem}.meta.yaml"
        policies: list = []
        if meta_path.is_file():
            meta = yaml.safe_load(meta_path.read_text(encoding="utf-8")) or {}
            policies = meta.get("policies") or []
        entry: dict = {"scenario": _repo_rel_posix(xosc_path)}
        entry["policies"] = policies
        scenarios.append(entry)

    return {
        "name": "scenario_authoring_catalog",
        "defaults": dict(_DEFAULTS),
        "scenarios": scenarios,
    }


def main() -> int:
    manifest = build()
    body = yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True, default_flow_style=False)
    _MANIFEST.write_text(_HEADER + body, encoding="utf-8")
    print(f"[manifest] {len(manifest['scenarios'])} scenarios -> {_MANIFEST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
