# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osi3/osi_motionrequest.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'osi3/osi_motionrequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osi3 import osi_common_pb2 as osi3_dot_osi__common__pb2
from osi3 import osi_version_pb2 as osi3_dot_osi__version__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cosi3/osi_motionrequest.proto\x12\x04osi3\x1a\x15osi3/osi_common.proto\x1a\x16osi3/osi_version.proto\"\x86\x05\n\rMotionRequest\x12\'\n\x07version\x18\x01 \x01(\x0b\x32\x16.osi3.InterfaceVersion\x12\"\n\ttimestamp\x18\x02 \x01(\x0b\x32\x0f.osi3.Timestamp\x12\x42\n\x13motion_request_type\x18\x03 \x01(\x0e\x32%.osi3.MotionRequest.MotionRequestType\x12\x37\n\rdesired_state\x18\x04 \x01(\x0b\x32 .osi3.MotionRequest.DesiredState\x12\x41\n\x12\x64\x65sired_trajectory\x18\x05 \x01(\x0b\x32%.osi3.MotionRequest.DesiredTrajectory\x1a\xc6\x01\n\x0c\x44\x65siredState\x12\"\n\ttimestamp\x18\x01 \x01(\x0b\x32\x0f.osi3.Timestamp\x12 \n\x08position\x18\x02 \x01(\x0b\x32\x0e.osi3.Vector3d\x12(\n\x0borientation\x18\x03 \x01(\x0b\x32\x13.osi3.Orientation3d\x12 \n\x08velocity\x18\x04 \x01(\x0b\x32\x0e.osi3.Vector3d\x12$\n\x0c\x61\x63\x63\x65leration\x18\x05 \x01(\x0b\x32\x0e.osi3.Vector3d\x1a?\n\x11\x44\x65siredTrajectory\x12*\n\x10trajectory_point\x18\x01 \x03(\x0b\x32\x10.osi3.StatePoint\"^\n\x11MotionRequestType\x12%\n!MOTION_REQUEST_TYPE_DESIRED_STATE\x10\x00\x12\"\n\x1eMOTION_REQUEST_TYPE_TRAJECTORY\x10\x01\x42\x02H\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osi3.osi_motionrequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\001'
  _globals['_MOTIONREQUEST']._serialized_start=86
  _globals['_MOTIONREQUEST']._serialized_end=732
  _globals['_MOTIONREQUEST_DESIREDSTATE']._serialized_start=373
  _globals['_MOTIONREQUEST_DESIREDSTATE']._serialized_end=571
  _globals['_MOTIONREQUEST_DESIREDTRAJECTORY']._serialized_start=573
  _globals['_MOTIONREQUEST_DESIREDTRAJECTORY']._serialized_end=636
  _globals['_MOTIONREQUEST_MOTIONREQUESTTYPE']._serialized_start=638
  _globals['_MOTIONREQUEST_MOTIONREQUESTTYPE']._serialized_end=732
# @@protoc_insertion_point(module_scope)
