from osi3 import osi_common_pb2 as _osi_common_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from collections.abc import Iterable as _Iterable, Mapping as _Mapping
from typing import ClassVar as _ClassVar, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class TrafficSignValue(_message.Message):
    __slots__ = ("value", "value_unit", "text")
    class Unit(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        UNIT_UNKNOWN: _ClassVar[TrafficSignValue.Unit]
        UNIT_OTHER: _ClassVar[TrafficSignValue.Unit]
        UNIT_NO_UNIT: _ClassVar[TrafficSignValue.Unit]
        UNIT_KILOMETER_PER_HOUR: _ClassVar[TrafficSignValue.Unit]
        UNIT_MILE_PER_HOUR: _ClassVar[TrafficSignValue.Unit]
        UNIT_METER: _ClassVar[TrafficSignValue.Unit]
        UNIT_KILOMETER: _ClassVar[TrafficSignValue.Unit]
        UNIT_FEET: _ClassVar[TrafficSignValue.Unit]
        UNIT_MILE: _ClassVar[TrafficSignValue.Unit]
        UNIT_METRIC_TON: _ClassVar[TrafficSignValue.Unit]
        UNIT_LONG_TON: _ClassVar[TrafficSignValue.Unit]
        UNIT_SHORT_TON: _ClassVar[TrafficSignValue.Unit]
        UNIT_HOUR: _ClassVar[TrafficSignValue.Unit]
        UNIT_MINUTES: _ClassVar[TrafficSignValue.Unit]
        UNIT_DAY_OF_MONTH: _ClassVar[TrafficSignValue.Unit]
        UNIT_DAY: _ClassVar[TrafficSignValue.Unit]
        UNIT_PERCENTAGE: _ClassVar[TrafficSignValue.Unit]
        UNIT_DURATION_DAY: _ClassVar[TrafficSignValue.Unit]
        UNIT_DURATION_HOUR: _ClassVar[TrafficSignValue.Unit]
        UNIT_DURATION_MINUTE: _ClassVar[TrafficSignValue.Unit]
    UNIT_UNKNOWN: TrafficSignValue.Unit
    UNIT_OTHER: TrafficSignValue.Unit
    UNIT_NO_UNIT: TrafficSignValue.Unit
    UNIT_KILOMETER_PER_HOUR: TrafficSignValue.Unit
    UNIT_MILE_PER_HOUR: TrafficSignValue.Unit
    UNIT_METER: TrafficSignValue.Unit
    UNIT_KILOMETER: TrafficSignValue.Unit
    UNIT_FEET: TrafficSignValue.Unit
    UNIT_MILE: TrafficSignValue.Unit
    UNIT_METRIC_TON: TrafficSignValue.Unit
    UNIT_LONG_TON: TrafficSignValue.Unit
    UNIT_SHORT_TON: TrafficSignValue.Unit
    UNIT_HOUR: TrafficSignValue.Unit
    UNIT_MINUTES: TrafficSignValue.Unit
    UNIT_DAY_OF_MONTH: TrafficSignValue.Unit
    UNIT_DAY: TrafficSignValue.Unit
    UNIT_PERCENTAGE: TrafficSignValue.Unit
    UNIT_DURATION_DAY: TrafficSignValue.Unit
    UNIT_DURATION_HOUR: TrafficSignValue.Unit
    UNIT_DURATION_MINUTE: TrafficSignValue.Unit
    VALUE_FIELD_NUMBER: _ClassVar[int]
    VALUE_UNIT_FIELD_NUMBER: _ClassVar[int]
    TEXT_FIELD_NUMBER: _ClassVar[int]
    value: float
    value_unit: TrafficSignValue.Unit
    text: str
    def __init__(self, value: _Optional[float] = ..., value_unit: _Optional[_Union[TrafficSignValue.Unit, str]] = ..., text: _Optional[str] = ...) -> None: ...

class TrafficSign(_message.Message):
    __slots__ = ("id", "main_sign", "supplementary_sign", "source_reference")
    class Variability(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        VARIABILITY_UNKNOWN: _ClassVar[TrafficSign.Variability]
        VARIABILITY_OTHER: _ClassVar[TrafficSign.Variability]
        VARIABILITY_FIXED: _ClassVar[TrafficSign.Variability]
        VARIABILITY_VARIABLE: _ClassVar[TrafficSign.Variability]
        VARIABILITY_MOVABLE: _ClassVar[TrafficSign.Variability]
        VARIABILITY_MUTABLE: _ClassVar[TrafficSign.Variability]
        VARIABILITY_MOVABLE_AND_MUTABLE: _ClassVar[TrafficSign.Variability]
    VARIABILITY_UNKNOWN: TrafficSign.Variability
    VARIABILITY_OTHER: TrafficSign.Variability
    VARIABILITY_FIXED: TrafficSign.Variability
    VARIABILITY_VARIABLE: TrafficSign.Variability
    VARIABILITY_MOVABLE: TrafficSign.Variability
    VARIABILITY_MUTABLE: TrafficSign.Variability
    VARIABILITY_MOVABLE_AND_MUTABLE: TrafficSign.Variability
    class MainSign(_message.Message):
        __slots__ = ("base", "classification", "model_reference")
        class Classification(_message.Message):
            __slots__ = ("variability", "type", "value", "direction_scope", "assigned_lane_id", "vertically_mirrored", "is_out_of_service", "country", "country_revision", "code", "sub_code", "logical_lane_assignment")
            class Type(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
                __slots__ = ()
                TYPE_UNKNOWN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_OTHER: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DANGER_SPOT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ZEBRA_CROSSING: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_FLIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CATTLE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HORSE_RIDERS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_AMPHIBIANS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_FALLING_ROCKS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SNOW_OR_ICE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_LOOSE_GRAVEL: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_WATERSIDE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CLEARANCE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_MOVABLE_BRIDGE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_RIGHT_BEFORE_LEFT_NEXT_INTERSECTION: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TURN_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TURN_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DOUBLE_TURN_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DOUBLE_TURN_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HILL_DOWNWARDS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HILL_UPWARDS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_UNEVEN_ROAD: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ROAD_SLIPPERY_WET_OR_DIRTY: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SIDE_WINDS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ROAD_NARROWING: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ROAD_NARROWING_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ROAD_NARROWING_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ROAD_WORKS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TRAFFIC_QUEUES: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TWO_WAY_TRAFFIC: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ATTENTION_TRAFFIC_LIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PEDESTRIANS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CHILDREN_CROSSING: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CYCLE_ROUTE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DEER_CROSSING: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_UNGATED_LEVEL_CROSSING: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_LEVEL_CROSSING_MARKER: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_RAILWAY_TRAFFIC_PRIORITY: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_GIVE_WAY: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_STOP: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRIORITY_TO_OPPOSITE_DIRECTION: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRIORITY_TO_OPPOSITE_DIRECTION_UPSIDE_DOWN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRESCRIBED_LEFT_TURN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRESCRIBED_RIGHT_TURN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRESCRIBED_STRAIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRESCRIBED_RIGHT_WAY: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRESCRIBED_LEFT_WAY: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRESCRIBED_RIGHT_TURN_AND_STRAIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRESCRIBED_LEFT_TURN_AND_STRAIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRESCRIBED_LEFT_TURN_AND_RIGHT_TURN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRESCRIBED_LEFT_TURN_RIGHT_TURN_AND_STRAIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ROUNDABOUT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ONEWAY_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ONEWAY_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PASS_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PASS_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SIDE_LANE_OPEN_FOR_TRAFFIC: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SIDE_LANE_CLOSED_FOR_TRAFFIC: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SIDE_LANE_CLOSING_FOR_TRAFFIC: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_BUS_STOP: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TAXI_STAND: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_BICYCLES_ONLY: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HORSE_RIDERS_ONLY: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PEDESTRIANS_ONLY: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_BICYCLES_PEDESTRIANS_SHARED_ONLY: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_BICYCLES_PEDESTRIANS_SEPARATED_LEFT_ONLY: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_BICYCLES_PEDESTRIANS_SEPARATED_RIGHT_ONLY: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PEDESTRIAN_ZONE_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PEDESTRIAN_ZONE_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_BICYCLE_ROAD_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_BICYCLE_ROAD_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_BUS_LANE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_BUS_LANE_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_BUS_LANE_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ALL_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_MOTORIZED_MULTITRACK_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TRUCKS_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_BICYCLES_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_MOTORCYCLES_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_MOPEDS_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HORSE_RIDERS_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HORSE_CARRIAGES_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CATTLE_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_BUSES_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CARS_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CARS_TRAILERS_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TRUCKS_TRAILERS_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TRACTORS_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PEDESTRIANS_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_MOTOR_VEHICLES_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HAZARDOUS_GOODS_VEHICLES_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_OVER_WEIGHT_VEHICLES_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_VEHICLES_AXLE_OVER_WEIGHT_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_VEHICLES_EXCESS_WIDTH_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_VEHICLES_EXCESS_HEIGHT_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_VEHICLES_EXCESS_LENGTH_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DO_NOT_ENTER: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SNOW_CHAINS_REQUIRED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_WATER_POLLUTANT_VEHICLES_PROHIBITED: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ENVIRONMENTAL_ZONE_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ENVIRONMENTAL_ZONE_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_NO_U_TURN_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_NO_U_TURN_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRESCRIBED_U_TURN_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRESCRIBED_U_TURN_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_MINIMUM_DISTANCE_FOR_TRUCKS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SPEED_LIMIT_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SPEED_LIMIT_ZONE_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SPEED_LIMIT_ZONE_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_MINIMUM_SPEED_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_OVERTAKING_BAN_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_OVERTAKING_BAN_FOR_TRUCKS_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SPEED_LIMIT_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_MINIMUM_SPEED_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_OVERTAKING_BAN_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_OVERTAKING_BAN_FOR_TRUCKS_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ALL_RESTRICTIONS_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_NO_STOPPING: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_NO_PARKING: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_NO_PARKING_ZONE_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_NO_PARKING_ZONE_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_RIGHT_OF_WAY_NEXT_INTERSECTION: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_RIGHT_OF_WAY_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_RIGHT_OF_WAY_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRIORITY_OVER_OPPOSITE_DIRECTION: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRIORITY_OVER_OPPOSITE_DIRECTION_UPSIDE_DOWN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TOWN_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TOWN_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CAR_PARKING: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CAR_PARKING_ZONE_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CAR_PARKING_ZONE_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SIDEWALK_HALF_PARKING_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SIDEWALK_HALF_PARKING_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SIDEWALK_PARKING_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SIDEWALK_PARKING_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SIDEWALK_PERPENDICULAR_HALF_PARKING_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SIDEWALK_PERPENDICULAR_HALF_PARKING_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SIDEWALK_PERPENDICULAR_PARKING_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SIDEWALK_PERPENDICULAR_PARKING_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_LIVING_STREET_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_LIVING_STREET_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TUNNEL: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_EMERGENCY_STOPPING_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_EMERGENCY_STOPPING_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HIGHWAY_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HIGHWAY_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_EXPRESSWAY_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_EXPRESSWAY_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_NAMED_HIGHWAY_EXIT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_NAMED_EXPRESSWAY_EXIT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_NAMED_ROAD_EXIT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HIGHWAY_EXIT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_EXPRESSWAY_EXIT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ONEWAY_STREET: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CROSSING_GUARDS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DEADEND: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DEADEND_EXCLUDING_DESIGNATED_ACTORS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_FIRST_AID_STATION: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_POLICE_STATION: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TELEPHONE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_FILLING_STATION: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HOTEL: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_INN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_KIOSK: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TOILET: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CHAPEL: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TOURIST_INFO: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_REPAIR_SERVICE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PEDESTRIAN_UNDERPASS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PEDESTRIAN_BRIDGE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CAMPER_PLACE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ADVISORY_SPEED_LIMIT_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ADVISORY_SPEED_LIMIT_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PLACE_NAME: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TOURIST_ATTRACTION: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TOURIST_ROUTE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TOURIST_AREA: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SHOULDER_NOT_PASSABLE_MOTOR_VEHICLES: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SHOULDER_UNSAFE_TRUCKS_TRACTORS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TOLL_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TOLL_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TOLL_ROAD: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CUSTOMS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_INTERNATIONAL_BORDER_INFO: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_STREETLIGHT_RED_BAND: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_FEDERAL_HIGHWAY_ROUTE_NUMBER: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HIGHWAY_ROUTE_NUMBER: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HIGHWAY_INTERCHANGE_NUMBER: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_EUROPEAN_ROUTE_NUMBER: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_FEDERAL_HIGHWAY_DIRECTION_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_FEDERAL_HIGHWAY_DIRECTION_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRIMARY_ROAD_DIRECTION_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PRIMARY_ROAD_DIRECTION_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SECONDARY_ROAD_DIRECTION_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_SECONDARY_ROAD_DIRECTION_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DIRECTION_DESIGNATED_ACTORS_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DIRECTION_DESIGNATED_ACTORS_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ROUTING_DESIGNATED_ACTORS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DIRECTION_TO_HIGHWAY_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DIRECTION_TO_HIGHWAY_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DIRECTION_TO_LOCAL_DESTINATION_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DIRECTION_TO_LOCAL_DESTINATION_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_CONSOLIDATED_DIRECTIONS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_STREET_NAME: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DIRECTION_PREANNOUNCEMENT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DIRECTION_PREANNOUNCEMENT_LANE_CONFIG: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DIRECTION_PREANNOUNCEMENT_HIGHWAY_ENTRIES: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HIGHWAY_ANNOUNCEMENT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_OTHER_ROAD_ANNOUNCEMENT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HIGHWAY_ANNOUNCEMENT_TRUCK_STOP: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HIGHWAY_PREANNOUNCEMENT_DIRECTIONS: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_POLE_EXIT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_HIGHWAY_DISTANCE_BOARD: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DETOUR_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DETOUR_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_NUMBERED_DETOUR: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DETOUR_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DETOUR_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DETOUR_ROUTING_BOARD: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_OPTIONAL_DETOUR: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_OPTIONAL_DETOUR_ROUTING: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ROUTE_RECOMMENDATION: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ROUTE_RECOMMENDATION_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ANNOUNCE_LANE_TRANSITION_LEFT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ANNOUNCE_LANE_TRANSITION_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ANNOUNCE_RIGHT_LANE_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ANNOUNCE_LEFT_LANE_END: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ANNOUNCE_RIGHT_LANE_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ANNOUNCE_LEFT_LANE_BEGIN: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_ANNOUNCE_LANE_CONSOLIDATION: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DETOUR_CITY_BLOCK: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_GATE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_POLE_WARNING: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TRAFFIC_CONE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_MOBILE_LANE_CLOSURE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_REFLECTOR_POST: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_DIRECTIONAL_BOARD_WARNING: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_GUIDING_PLATE: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_GUIDING_PLATE_WEDGES: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_PARKING_HAZARD: _ClassVar[TrafficSign.MainSign.Classification.Type]
                TYPE_TRAFFIC_LIGHT_GREEN_ARROW: _ClassVar[TrafficSign.MainSign.Classification.Type]
            TYPE_UNKNOWN: TrafficSign.MainSign.Classification.Type
            TYPE_OTHER: TrafficSign.MainSign.Classification.Type
            TYPE_DANGER_SPOT: TrafficSign.MainSign.Classification.Type
            TYPE_ZEBRA_CROSSING: TrafficSign.MainSign.Classification.Type
            TYPE_FLIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_CATTLE: TrafficSign.MainSign.Classification.Type
            TYPE_HORSE_RIDERS: TrafficSign.MainSign.Classification.Type
            TYPE_AMPHIBIANS: TrafficSign.MainSign.Classification.Type
            TYPE_FALLING_ROCKS: TrafficSign.MainSign.Classification.Type
            TYPE_SNOW_OR_ICE: TrafficSign.MainSign.Classification.Type
            TYPE_LOOSE_GRAVEL: TrafficSign.MainSign.Classification.Type
            TYPE_WATERSIDE: TrafficSign.MainSign.Classification.Type
            TYPE_CLEARANCE: TrafficSign.MainSign.Classification.Type
            TYPE_MOVABLE_BRIDGE: TrafficSign.MainSign.Classification.Type
            TYPE_RIGHT_BEFORE_LEFT_NEXT_INTERSECTION: TrafficSign.MainSign.Classification.Type
            TYPE_TURN_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_TURN_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_DOUBLE_TURN_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_DOUBLE_TURN_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_HILL_DOWNWARDS: TrafficSign.MainSign.Classification.Type
            TYPE_HILL_UPWARDS: TrafficSign.MainSign.Classification.Type
            TYPE_UNEVEN_ROAD: TrafficSign.MainSign.Classification.Type
            TYPE_ROAD_SLIPPERY_WET_OR_DIRTY: TrafficSign.MainSign.Classification.Type
            TYPE_SIDE_WINDS: TrafficSign.MainSign.Classification.Type
            TYPE_ROAD_NARROWING: TrafficSign.MainSign.Classification.Type
            TYPE_ROAD_NARROWING_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_ROAD_NARROWING_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_ROAD_WORKS: TrafficSign.MainSign.Classification.Type
            TYPE_TRAFFIC_QUEUES: TrafficSign.MainSign.Classification.Type
            TYPE_TWO_WAY_TRAFFIC: TrafficSign.MainSign.Classification.Type
            TYPE_ATTENTION_TRAFFIC_LIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_PEDESTRIANS: TrafficSign.MainSign.Classification.Type
            TYPE_CHILDREN_CROSSING: TrafficSign.MainSign.Classification.Type
            TYPE_CYCLE_ROUTE: TrafficSign.MainSign.Classification.Type
            TYPE_DEER_CROSSING: TrafficSign.MainSign.Classification.Type
            TYPE_UNGATED_LEVEL_CROSSING: TrafficSign.MainSign.Classification.Type
            TYPE_LEVEL_CROSSING_MARKER: TrafficSign.MainSign.Classification.Type
            TYPE_RAILWAY_TRAFFIC_PRIORITY: TrafficSign.MainSign.Classification.Type
            TYPE_GIVE_WAY: TrafficSign.MainSign.Classification.Type
            TYPE_STOP: TrafficSign.MainSign.Classification.Type
            TYPE_PRIORITY_TO_OPPOSITE_DIRECTION: TrafficSign.MainSign.Classification.Type
            TYPE_PRIORITY_TO_OPPOSITE_DIRECTION_UPSIDE_DOWN: TrafficSign.MainSign.Classification.Type
            TYPE_PRESCRIBED_LEFT_TURN: TrafficSign.MainSign.Classification.Type
            TYPE_PRESCRIBED_RIGHT_TURN: TrafficSign.MainSign.Classification.Type
            TYPE_PRESCRIBED_STRAIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_PRESCRIBED_RIGHT_WAY: TrafficSign.MainSign.Classification.Type
            TYPE_PRESCRIBED_LEFT_WAY: TrafficSign.MainSign.Classification.Type
            TYPE_PRESCRIBED_RIGHT_TURN_AND_STRAIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_PRESCRIBED_LEFT_TURN_AND_STRAIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_PRESCRIBED_LEFT_TURN_AND_RIGHT_TURN: TrafficSign.MainSign.Classification.Type
            TYPE_PRESCRIBED_LEFT_TURN_RIGHT_TURN_AND_STRAIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_ROUNDABOUT: TrafficSign.MainSign.Classification.Type
            TYPE_ONEWAY_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_ONEWAY_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_PASS_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_PASS_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_SIDE_LANE_OPEN_FOR_TRAFFIC: TrafficSign.MainSign.Classification.Type
            TYPE_SIDE_LANE_CLOSED_FOR_TRAFFIC: TrafficSign.MainSign.Classification.Type
            TYPE_SIDE_LANE_CLOSING_FOR_TRAFFIC: TrafficSign.MainSign.Classification.Type
            TYPE_BUS_STOP: TrafficSign.MainSign.Classification.Type
            TYPE_TAXI_STAND: TrafficSign.MainSign.Classification.Type
            TYPE_BICYCLES_ONLY: TrafficSign.MainSign.Classification.Type
            TYPE_HORSE_RIDERS_ONLY: TrafficSign.MainSign.Classification.Type
            TYPE_PEDESTRIANS_ONLY: TrafficSign.MainSign.Classification.Type
            TYPE_BICYCLES_PEDESTRIANS_SHARED_ONLY: TrafficSign.MainSign.Classification.Type
            TYPE_BICYCLES_PEDESTRIANS_SEPARATED_LEFT_ONLY: TrafficSign.MainSign.Classification.Type
            TYPE_BICYCLES_PEDESTRIANS_SEPARATED_RIGHT_ONLY: TrafficSign.MainSign.Classification.Type
            TYPE_PEDESTRIAN_ZONE_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_PEDESTRIAN_ZONE_END: TrafficSign.MainSign.Classification.Type
            TYPE_BICYCLE_ROAD_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_BICYCLE_ROAD_END: TrafficSign.MainSign.Classification.Type
            TYPE_BUS_LANE: TrafficSign.MainSign.Classification.Type
            TYPE_BUS_LANE_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_BUS_LANE_END: TrafficSign.MainSign.Classification.Type
            TYPE_ALL_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_MOTORIZED_MULTITRACK_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_TRUCKS_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_BICYCLES_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_MOTORCYCLES_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_MOPEDS_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_HORSE_RIDERS_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_HORSE_CARRIAGES_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_CATTLE_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_BUSES_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_CARS_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_CARS_TRAILERS_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_TRUCKS_TRAILERS_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_TRACTORS_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_PEDESTRIANS_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_MOTOR_VEHICLES_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_HAZARDOUS_GOODS_VEHICLES_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_OVER_WEIGHT_VEHICLES_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_VEHICLES_AXLE_OVER_WEIGHT_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_VEHICLES_EXCESS_WIDTH_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_VEHICLES_EXCESS_HEIGHT_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_VEHICLES_EXCESS_LENGTH_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_DO_NOT_ENTER: TrafficSign.MainSign.Classification.Type
            TYPE_SNOW_CHAINS_REQUIRED: TrafficSign.MainSign.Classification.Type
            TYPE_WATER_POLLUTANT_VEHICLES_PROHIBITED: TrafficSign.MainSign.Classification.Type
            TYPE_ENVIRONMENTAL_ZONE_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_ENVIRONMENTAL_ZONE_END: TrafficSign.MainSign.Classification.Type
            TYPE_NO_U_TURN_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_NO_U_TURN_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_PRESCRIBED_U_TURN_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_PRESCRIBED_U_TURN_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_MINIMUM_DISTANCE_FOR_TRUCKS: TrafficSign.MainSign.Classification.Type
            TYPE_SPEED_LIMIT_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_SPEED_LIMIT_ZONE_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_SPEED_LIMIT_ZONE_END: TrafficSign.MainSign.Classification.Type
            TYPE_MINIMUM_SPEED_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_OVERTAKING_BAN_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_OVERTAKING_BAN_FOR_TRUCKS_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_SPEED_LIMIT_END: TrafficSign.MainSign.Classification.Type
            TYPE_MINIMUM_SPEED_END: TrafficSign.MainSign.Classification.Type
            TYPE_OVERTAKING_BAN_END: TrafficSign.MainSign.Classification.Type
            TYPE_OVERTAKING_BAN_FOR_TRUCKS_END: TrafficSign.MainSign.Classification.Type
            TYPE_ALL_RESTRICTIONS_END: TrafficSign.MainSign.Classification.Type
            TYPE_NO_STOPPING: TrafficSign.MainSign.Classification.Type
            TYPE_NO_PARKING: TrafficSign.MainSign.Classification.Type
            TYPE_NO_PARKING_ZONE_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_NO_PARKING_ZONE_END: TrafficSign.MainSign.Classification.Type
            TYPE_RIGHT_OF_WAY_NEXT_INTERSECTION: TrafficSign.MainSign.Classification.Type
            TYPE_RIGHT_OF_WAY_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_RIGHT_OF_WAY_END: TrafficSign.MainSign.Classification.Type
            TYPE_PRIORITY_OVER_OPPOSITE_DIRECTION: TrafficSign.MainSign.Classification.Type
            TYPE_PRIORITY_OVER_OPPOSITE_DIRECTION_UPSIDE_DOWN: TrafficSign.MainSign.Classification.Type
            TYPE_TOWN_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_TOWN_END: TrafficSign.MainSign.Classification.Type
            TYPE_CAR_PARKING: TrafficSign.MainSign.Classification.Type
            TYPE_CAR_PARKING_ZONE_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_CAR_PARKING_ZONE_END: TrafficSign.MainSign.Classification.Type
            TYPE_SIDEWALK_HALF_PARKING_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_SIDEWALK_HALF_PARKING_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_SIDEWALK_PARKING_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_SIDEWALK_PARKING_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_SIDEWALK_PERPENDICULAR_HALF_PARKING_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_SIDEWALK_PERPENDICULAR_HALF_PARKING_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_SIDEWALK_PERPENDICULAR_PARKING_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_SIDEWALK_PERPENDICULAR_PARKING_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_LIVING_STREET_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_LIVING_STREET_END: TrafficSign.MainSign.Classification.Type
            TYPE_TUNNEL: TrafficSign.MainSign.Classification.Type
            TYPE_EMERGENCY_STOPPING_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_EMERGENCY_STOPPING_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_HIGHWAY_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_HIGHWAY_END: TrafficSign.MainSign.Classification.Type
            TYPE_EXPRESSWAY_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_EXPRESSWAY_END: TrafficSign.MainSign.Classification.Type
            TYPE_NAMED_HIGHWAY_EXIT: TrafficSign.MainSign.Classification.Type
            TYPE_NAMED_EXPRESSWAY_EXIT: TrafficSign.MainSign.Classification.Type
            TYPE_NAMED_ROAD_EXIT: TrafficSign.MainSign.Classification.Type
            TYPE_HIGHWAY_EXIT: TrafficSign.MainSign.Classification.Type
            TYPE_EXPRESSWAY_EXIT: TrafficSign.MainSign.Classification.Type
            TYPE_ONEWAY_STREET: TrafficSign.MainSign.Classification.Type
            TYPE_CROSSING_GUARDS: TrafficSign.MainSign.Classification.Type
            TYPE_DEADEND: TrafficSign.MainSign.Classification.Type
            TYPE_DEADEND_EXCLUDING_DESIGNATED_ACTORS: TrafficSign.MainSign.Classification.Type
            TYPE_FIRST_AID_STATION: TrafficSign.MainSign.Classification.Type
            TYPE_POLICE_STATION: TrafficSign.MainSign.Classification.Type
            TYPE_TELEPHONE: TrafficSign.MainSign.Classification.Type
            TYPE_FILLING_STATION: TrafficSign.MainSign.Classification.Type
            TYPE_HOTEL: TrafficSign.MainSign.Classification.Type
            TYPE_INN: TrafficSign.MainSign.Classification.Type
            TYPE_KIOSK: TrafficSign.MainSign.Classification.Type
            TYPE_TOILET: TrafficSign.MainSign.Classification.Type
            TYPE_CHAPEL: TrafficSign.MainSign.Classification.Type
            TYPE_TOURIST_INFO: TrafficSign.MainSign.Classification.Type
            TYPE_REPAIR_SERVICE: TrafficSign.MainSign.Classification.Type
            TYPE_PEDESTRIAN_UNDERPASS: TrafficSign.MainSign.Classification.Type
            TYPE_PEDESTRIAN_BRIDGE: TrafficSign.MainSign.Classification.Type
            TYPE_CAMPER_PLACE: TrafficSign.MainSign.Classification.Type
            TYPE_ADVISORY_SPEED_LIMIT_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_ADVISORY_SPEED_LIMIT_END: TrafficSign.MainSign.Classification.Type
            TYPE_PLACE_NAME: TrafficSign.MainSign.Classification.Type
            TYPE_TOURIST_ATTRACTION: TrafficSign.MainSign.Classification.Type
            TYPE_TOURIST_ROUTE: TrafficSign.MainSign.Classification.Type
            TYPE_TOURIST_AREA: TrafficSign.MainSign.Classification.Type
            TYPE_SHOULDER_NOT_PASSABLE_MOTOR_VEHICLES: TrafficSign.MainSign.Classification.Type
            TYPE_SHOULDER_UNSAFE_TRUCKS_TRACTORS: TrafficSign.MainSign.Classification.Type
            TYPE_TOLL_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_TOLL_END: TrafficSign.MainSign.Classification.Type
            TYPE_TOLL_ROAD: TrafficSign.MainSign.Classification.Type
            TYPE_CUSTOMS: TrafficSign.MainSign.Classification.Type
            TYPE_INTERNATIONAL_BORDER_INFO: TrafficSign.MainSign.Classification.Type
            TYPE_STREETLIGHT_RED_BAND: TrafficSign.MainSign.Classification.Type
            TYPE_FEDERAL_HIGHWAY_ROUTE_NUMBER: TrafficSign.MainSign.Classification.Type
            TYPE_HIGHWAY_ROUTE_NUMBER: TrafficSign.MainSign.Classification.Type
            TYPE_HIGHWAY_INTERCHANGE_NUMBER: TrafficSign.MainSign.Classification.Type
            TYPE_EUROPEAN_ROUTE_NUMBER: TrafficSign.MainSign.Classification.Type
            TYPE_FEDERAL_HIGHWAY_DIRECTION_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_FEDERAL_HIGHWAY_DIRECTION_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_PRIMARY_ROAD_DIRECTION_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_PRIMARY_ROAD_DIRECTION_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_SECONDARY_ROAD_DIRECTION_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_SECONDARY_ROAD_DIRECTION_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_DIRECTION_DESIGNATED_ACTORS_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_DIRECTION_DESIGNATED_ACTORS_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_ROUTING_DESIGNATED_ACTORS: TrafficSign.MainSign.Classification.Type
            TYPE_DIRECTION_TO_HIGHWAY_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_DIRECTION_TO_HIGHWAY_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_DIRECTION_TO_LOCAL_DESTINATION_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_DIRECTION_TO_LOCAL_DESTINATION_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_CONSOLIDATED_DIRECTIONS: TrafficSign.MainSign.Classification.Type
            TYPE_STREET_NAME: TrafficSign.MainSign.Classification.Type
            TYPE_DIRECTION_PREANNOUNCEMENT: TrafficSign.MainSign.Classification.Type
            TYPE_DIRECTION_PREANNOUNCEMENT_LANE_CONFIG: TrafficSign.MainSign.Classification.Type
            TYPE_DIRECTION_PREANNOUNCEMENT_HIGHWAY_ENTRIES: TrafficSign.MainSign.Classification.Type
            TYPE_HIGHWAY_ANNOUNCEMENT: TrafficSign.MainSign.Classification.Type
            TYPE_OTHER_ROAD_ANNOUNCEMENT: TrafficSign.MainSign.Classification.Type
            TYPE_HIGHWAY_ANNOUNCEMENT_TRUCK_STOP: TrafficSign.MainSign.Classification.Type
            TYPE_HIGHWAY_PREANNOUNCEMENT_DIRECTIONS: TrafficSign.MainSign.Classification.Type
            TYPE_POLE_EXIT: TrafficSign.MainSign.Classification.Type
            TYPE_HIGHWAY_DISTANCE_BOARD: TrafficSign.MainSign.Classification.Type
            TYPE_DETOUR_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_DETOUR_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_NUMBERED_DETOUR: TrafficSign.MainSign.Classification.Type
            TYPE_DETOUR_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_DETOUR_END: TrafficSign.MainSign.Classification.Type
            TYPE_DETOUR_ROUTING_BOARD: TrafficSign.MainSign.Classification.Type
            TYPE_OPTIONAL_DETOUR: TrafficSign.MainSign.Classification.Type
            TYPE_OPTIONAL_DETOUR_ROUTING: TrafficSign.MainSign.Classification.Type
            TYPE_ROUTE_RECOMMENDATION: TrafficSign.MainSign.Classification.Type
            TYPE_ROUTE_RECOMMENDATION_END: TrafficSign.MainSign.Classification.Type
            TYPE_ANNOUNCE_LANE_TRANSITION_LEFT: TrafficSign.MainSign.Classification.Type
            TYPE_ANNOUNCE_LANE_TRANSITION_RIGHT: TrafficSign.MainSign.Classification.Type
            TYPE_ANNOUNCE_RIGHT_LANE_END: TrafficSign.MainSign.Classification.Type
            TYPE_ANNOUNCE_LEFT_LANE_END: TrafficSign.MainSign.Classification.Type
            TYPE_ANNOUNCE_RIGHT_LANE_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_ANNOUNCE_LEFT_LANE_BEGIN: TrafficSign.MainSign.Classification.Type
            TYPE_ANNOUNCE_LANE_CONSOLIDATION: TrafficSign.MainSign.Classification.Type
            TYPE_DETOUR_CITY_BLOCK: TrafficSign.MainSign.Classification.Type
            TYPE_GATE: TrafficSign.MainSign.Classification.Type
            TYPE_POLE_WARNING: TrafficSign.MainSign.Classification.Type
            TYPE_TRAFFIC_CONE: TrafficSign.MainSign.Classification.Type
            TYPE_MOBILE_LANE_CLOSURE: TrafficSign.MainSign.Classification.Type
            TYPE_REFLECTOR_POST: TrafficSign.MainSign.Classification.Type
            TYPE_DIRECTIONAL_BOARD_WARNING: TrafficSign.MainSign.Classification.Type
            TYPE_GUIDING_PLATE: TrafficSign.MainSign.Classification.Type
            TYPE_GUIDING_PLATE_WEDGES: TrafficSign.MainSign.Classification.Type
            TYPE_PARKING_HAZARD: TrafficSign.MainSign.Classification.Type
            TYPE_TRAFFIC_LIGHT_GREEN_ARROW: TrafficSign.MainSign.Classification.Type
            class DirectionScope(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
                __slots__ = ()
                DIRECTION_SCOPE_UNKNOWN: _ClassVar[TrafficSign.MainSign.Classification.DirectionScope]
                DIRECTION_SCOPE_OTHER: _ClassVar[TrafficSign.MainSign.Classification.DirectionScope]
                DIRECTION_SCOPE_NO_DIRECTION: _ClassVar[TrafficSign.MainSign.Classification.DirectionScope]
                DIRECTION_SCOPE_LEFT: _ClassVar[TrafficSign.MainSign.Classification.DirectionScope]
                DIRECTION_SCOPE_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.DirectionScope]
                DIRECTION_SCOPE_LEFT_RIGHT: _ClassVar[TrafficSign.MainSign.Classification.DirectionScope]
            DIRECTION_SCOPE_UNKNOWN: TrafficSign.MainSign.Classification.DirectionScope
            DIRECTION_SCOPE_OTHER: TrafficSign.MainSign.Classification.DirectionScope
            DIRECTION_SCOPE_NO_DIRECTION: TrafficSign.MainSign.Classification.DirectionScope
            DIRECTION_SCOPE_LEFT: TrafficSign.MainSign.Classification.DirectionScope
            DIRECTION_SCOPE_RIGHT: TrafficSign.MainSign.Classification.DirectionScope
            DIRECTION_SCOPE_LEFT_RIGHT: TrafficSign.MainSign.Classification.DirectionScope
            VARIABILITY_FIELD_NUMBER: _ClassVar[int]
            TYPE_FIELD_NUMBER: _ClassVar[int]
            VALUE_FIELD_NUMBER: _ClassVar[int]
            DIRECTION_SCOPE_FIELD_NUMBER: _ClassVar[int]
            ASSIGNED_LANE_ID_FIELD_NUMBER: _ClassVar[int]
            VERTICALLY_MIRRORED_FIELD_NUMBER: _ClassVar[int]
            IS_OUT_OF_SERVICE_FIELD_NUMBER: _ClassVar[int]
            COUNTRY_FIELD_NUMBER: _ClassVar[int]
            COUNTRY_REVISION_FIELD_NUMBER: _ClassVar[int]
            CODE_FIELD_NUMBER: _ClassVar[int]
            SUB_CODE_FIELD_NUMBER: _ClassVar[int]
            LOGICAL_LANE_ASSIGNMENT_FIELD_NUMBER: _ClassVar[int]
            variability: TrafficSign.Variability
            type: TrafficSign.MainSign.Classification.Type
            value: TrafficSignValue
            direction_scope: TrafficSign.MainSign.Classification.DirectionScope
            assigned_lane_id: _containers.RepeatedCompositeFieldContainer[_osi_common_pb2.Identifier]
            vertically_mirrored: bool
            is_out_of_service: bool
            country: str
            country_revision: str
            code: str
            sub_code: str
            logical_lane_assignment: _containers.RepeatedCompositeFieldContainer[_osi_common_pb2.LogicalLaneAssignment]
            def __init__(self, variability: _Optional[_Union[TrafficSign.Variability, str]] = ..., type: _Optional[_Union[TrafficSign.MainSign.Classification.Type, str]] = ..., value: _Optional[_Union[TrafficSignValue, _Mapping]] = ..., direction_scope: _Optional[_Union[TrafficSign.MainSign.Classification.DirectionScope, str]] = ..., assigned_lane_id: _Optional[_Iterable[_Union[_osi_common_pb2.Identifier, _Mapping]]] = ..., vertically_mirrored: bool = ..., is_out_of_service: bool = ..., country: _Optional[str] = ..., country_revision: _Optional[str] = ..., code: _Optional[str] = ..., sub_code: _Optional[str] = ..., logical_lane_assignment: _Optional[_Iterable[_Union[_osi_common_pb2.LogicalLaneAssignment, _Mapping]]] = ...) -> None: ...
        BASE_FIELD_NUMBER: _ClassVar[int]
        CLASSIFICATION_FIELD_NUMBER: _ClassVar[int]
        MODEL_REFERENCE_FIELD_NUMBER: _ClassVar[int]
        base: _osi_common_pb2.BaseStationary
        classification: TrafficSign.MainSign.Classification
        model_reference: str
        def __init__(self, base: _Optional[_Union[_osi_common_pb2.BaseStationary, _Mapping]] = ..., classification: _Optional[_Union[TrafficSign.MainSign.Classification, _Mapping]] = ..., model_reference: _Optional[str] = ...) -> None: ...
    class SupplementarySign(_message.Message):
        __slots__ = ("base", "classification", "model_reference")
        class Classification(_message.Message):
            __slots__ = ("variability", "type", "value", "assigned_lane_id", "actor", "arrow", "is_out_of_service", "country", "country_revision", "code", "sub_code", "logical_lane_assignment")
            class Type(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
                __slots__ = ()
                TYPE_UNKNOWN: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_OTHER: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_NO_SIGN: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_TEXT: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_SPACE: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_TIME: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_ARROW: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_CONSTRAINED_TO: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_EXCEPT: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_VALID_FOR_DISTANCE: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_PRIORITY_ROAD_BOTTOM_LEFT_FOUR_WAY: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_PRIORITY_ROAD_TOP_LEFT_FOUR_WAY: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_PRIORITY_ROAD_BOTTOM_LEFT_THREE_WAY_STRAIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_PRIORITY_ROAD_BOTTOM_LEFT_THREE_WAY_SIDEWAYS: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_PRIORITY_ROAD_TOP_LEFT_THREE_WAY_STRAIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_PRIORITY_ROAD_BOTTOM_RIGHT_FOUR_WAY: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_PRIORITY_ROAD_TOP_RIGHT_FOUR_WAY: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_PRIORITY_ROAD_BOTTOM_RIGHT_THREE_WAY_STRAIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_PRIORITY_ROAD_BOTTOM_RIGHT_THREE_WAY_SIDEWAY: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_PRIORITY_ROAD_TOP_RIGHT_THREE_WAY_STRAIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_VALID_IN_DISTANCE: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_STOP_IN: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_LEFT_ARROW: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_LEFT_BEND_ARROW: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_RIGHT_ARROW: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_RIGHT_BEND_ARROW: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_ACCIDENT: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_SNOW: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_FOG: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_ROLLING_HIGHWAY_INFORMATION: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_SERVICES: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_TIME_RANGE: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_PARKING_DISC_TIME_RESTRICTION: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_WEIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_WET: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_PARKING_CONSTRAINT: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_NO_WAITING_SIDE_STRIPES: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_RAIN: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_SNOW_RAIN: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_NIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_STOP_4_WAY: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_TRUCK: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_TRACTORS_MAY_BE_PASSED: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_HAZARDOUS: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_TRAILER: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_ZONE: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_MOTORCYCLE: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_MOTORCYCLE_ALLOWED: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
                TYPE_CAR: _ClassVar[TrafficSign.SupplementarySign.Classification.Type]
            TYPE_UNKNOWN: TrafficSign.SupplementarySign.Classification.Type
            TYPE_OTHER: TrafficSign.SupplementarySign.Classification.Type
            TYPE_NO_SIGN: TrafficSign.SupplementarySign.Classification.Type
            TYPE_TEXT: TrafficSign.SupplementarySign.Classification.Type
            TYPE_SPACE: TrafficSign.SupplementarySign.Classification.Type
            TYPE_TIME: TrafficSign.SupplementarySign.Classification.Type
            TYPE_ARROW: TrafficSign.SupplementarySign.Classification.Type
            TYPE_CONSTRAINED_TO: TrafficSign.SupplementarySign.Classification.Type
            TYPE_EXCEPT: TrafficSign.SupplementarySign.Classification.Type
            TYPE_VALID_FOR_DISTANCE: TrafficSign.SupplementarySign.Classification.Type
            TYPE_PRIORITY_ROAD_BOTTOM_LEFT_FOUR_WAY: TrafficSign.SupplementarySign.Classification.Type
            TYPE_PRIORITY_ROAD_TOP_LEFT_FOUR_WAY: TrafficSign.SupplementarySign.Classification.Type
            TYPE_PRIORITY_ROAD_BOTTOM_LEFT_THREE_WAY_STRAIGHT: TrafficSign.SupplementarySign.Classification.Type
            TYPE_PRIORITY_ROAD_BOTTOM_LEFT_THREE_WAY_SIDEWAYS: TrafficSign.SupplementarySign.Classification.Type
            TYPE_PRIORITY_ROAD_TOP_LEFT_THREE_WAY_STRAIGHT: TrafficSign.SupplementarySign.Classification.Type
            TYPE_PRIORITY_ROAD_BOTTOM_RIGHT_FOUR_WAY: TrafficSign.SupplementarySign.Classification.Type
            TYPE_PRIORITY_ROAD_TOP_RIGHT_FOUR_WAY: TrafficSign.SupplementarySign.Classification.Type
            TYPE_PRIORITY_ROAD_BOTTOM_RIGHT_THREE_WAY_STRAIGHT: TrafficSign.SupplementarySign.Classification.Type
            TYPE_PRIORITY_ROAD_BOTTOM_RIGHT_THREE_WAY_SIDEWAY: TrafficSign.SupplementarySign.Classification.Type
            TYPE_PRIORITY_ROAD_TOP_RIGHT_THREE_WAY_STRAIGHT: TrafficSign.SupplementarySign.Classification.Type
            TYPE_VALID_IN_DISTANCE: TrafficSign.SupplementarySign.Classification.Type
            TYPE_STOP_IN: TrafficSign.SupplementarySign.Classification.Type
            TYPE_LEFT_ARROW: TrafficSign.SupplementarySign.Classification.Type
            TYPE_LEFT_BEND_ARROW: TrafficSign.SupplementarySign.Classification.Type
            TYPE_RIGHT_ARROW: TrafficSign.SupplementarySign.Classification.Type
            TYPE_RIGHT_BEND_ARROW: TrafficSign.SupplementarySign.Classification.Type
            TYPE_ACCIDENT: TrafficSign.SupplementarySign.Classification.Type
            TYPE_SNOW: TrafficSign.SupplementarySign.Classification.Type
            TYPE_FOG: TrafficSign.SupplementarySign.Classification.Type
            TYPE_ROLLING_HIGHWAY_INFORMATION: TrafficSign.SupplementarySign.Classification.Type
            TYPE_SERVICES: TrafficSign.SupplementarySign.Classification.Type
            TYPE_TIME_RANGE: TrafficSign.SupplementarySign.Classification.Type
            TYPE_PARKING_DISC_TIME_RESTRICTION: TrafficSign.SupplementarySign.Classification.Type
            TYPE_WEIGHT: TrafficSign.SupplementarySign.Classification.Type
            TYPE_WET: TrafficSign.SupplementarySign.Classification.Type
            TYPE_PARKING_CONSTRAINT: TrafficSign.SupplementarySign.Classification.Type
            TYPE_NO_WAITING_SIDE_STRIPES: TrafficSign.SupplementarySign.Classification.Type
            TYPE_RAIN: TrafficSign.SupplementarySign.Classification.Type
            TYPE_SNOW_RAIN: TrafficSign.SupplementarySign.Classification.Type
            TYPE_NIGHT: TrafficSign.SupplementarySign.Classification.Type
            TYPE_STOP_4_WAY: TrafficSign.SupplementarySign.Classification.Type
            TYPE_TRUCK: TrafficSign.SupplementarySign.Classification.Type
            TYPE_TRACTORS_MAY_BE_PASSED: TrafficSign.SupplementarySign.Classification.Type
            TYPE_HAZARDOUS: TrafficSign.SupplementarySign.Classification.Type
            TYPE_TRAILER: TrafficSign.SupplementarySign.Classification.Type
            TYPE_ZONE: TrafficSign.SupplementarySign.Classification.Type
            TYPE_MOTORCYCLE: TrafficSign.SupplementarySign.Classification.Type
            TYPE_MOTORCYCLE_ALLOWED: TrafficSign.SupplementarySign.Classification.Type
            TYPE_CAR: TrafficSign.SupplementarySign.Classification.Type
            class Actor(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
                __slots__ = ()
                ACTOR_UNKNOWN: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_OTHER: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_NO_ACTOR: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_AGRICULTURAL_VEHICLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_BICYCLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_BUSES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_CAMPERS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_CARAVANS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_CARS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_CARS_WITH_CARAVANS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_CARS_WITH_TRAILERS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_CATTLE: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_CHILDREN: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_CONSTRUCTION_VEHICLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_DELIVERY_VEHICLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_DISABLED_PERSONS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_EBIKES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_ELECTRIC_VEHICLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_EMERGENCY_VEHICLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_FERRY_USERS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_FORESTRY_VEHICLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_HAZARDOUS_GOODS_VEHICLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_HORSE_CARRIAGES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_HORSE_RIDERS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_INLINE_SKATERS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_MEDICAL_VEHICLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_MILITARY_VEHICLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_MOPEDS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_MOTORCYCLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_MOTORIZED_MULTITRACK_VEHICLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_OPERATIONAL_AND_UTILITY_VEHICLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_PEDESTRIANS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_PUBLIC_TRANSPORT_VEHICLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_RAILROAD_TRAFFIC: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_RESIDENTS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_SLURRY_TRANSPORT: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_TAXIS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_TRACTORS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_TRAILERS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_TRAMS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_TRUCKS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_TRUCKS_WITH_SEMITRAILERS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_TRUCKS_WITH_TRAILERS: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_VEHICLES_WITH_GREEN_BADGES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_VEHICLES_WITH_RED_BADGES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_VEHICLES_WITH_YELLOW_BADGES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_WATER_POLLUTANT_VEHICLES: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
                ACTOR_WINTER_SPORTSPEOPLE: _ClassVar[TrafficSign.SupplementarySign.Classification.Actor]
            ACTOR_UNKNOWN: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_OTHER: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_NO_ACTOR: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_AGRICULTURAL_VEHICLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_BICYCLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_BUSES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_CAMPERS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_CARAVANS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_CARS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_CARS_WITH_CARAVANS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_CARS_WITH_TRAILERS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_CATTLE: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_CHILDREN: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_CONSTRUCTION_VEHICLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_DELIVERY_VEHICLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_DISABLED_PERSONS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_EBIKES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_ELECTRIC_VEHICLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_EMERGENCY_VEHICLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_FERRY_USERS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_FORESTRY_VEHICLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_HAZARDOUS_GOODS_VEHICLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_HORSE_CARRIAGES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_HORSE_RIDERS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_INLINE_SKATERS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_MEDICAL_VEHICLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_MILITARY_VEHICLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_MOPEDS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_MOTORCYCLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_MOTORIZED_MULTITRACK_VEHICLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_OPERATIONAL_AND_UTILITY_VEHICLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_PEDESTRIANS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_PUBLIC_TRANSPORT_VEHICLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_RAILROAD_TRAFFIC: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_RESIDENTS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_SLURRY_TRANSPORT: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_TAXIS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_TRACTORS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_TRAILERS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_TRAMS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_TRUCKS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_TRUCKS_WITH_SEMITRAILERS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_TRUCKS_WITH_TRAILERS: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_VEHICLES_WITH_GREEN_BADGES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_VEHICLES_WITH_RED_BADGES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_VEHICLES_WITH_YELLOW_BADGES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_WATER_POLLUTANT_VEHICLES: TrafficSign.SupplementarySign.Classification.Actor
            ACTOR_WINTER_SPORTSPEOPLE: TrafficSign.SupplementarySign.Classification.Actor
            class Arrow(_message.Message):
                __slots__ = ("lane_id", "direction")
                class Direction(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
                    __slots__ = ()
                    DIRECTION_UNKNOWN: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_OTHER: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_NO_DIRECTION: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_DIRECT_0_DEG: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_DIRECT_45_DEG_RIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_DIRECT_45_DEG_LEFT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_DIRECT_90_DEG_RIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_DIRECT_90_DEG_LEFT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_DIRECT_135_DEG_RIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_DIRECT_135_DEG_LEFT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_DIRECT_180_DEG: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_TURN_45_DEG_RIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_TURN_45_DEG_LEFT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_TURN_90_DEG_RIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_TURN_90_DEG_LEFT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_TURN_135_DEG_RIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_TURN_135_DEG_LEFT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_TURN_180_DEG_RIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_TURN_180_DEG_LEFT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_CIRCLE_0_DEG: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_CIRCLE_45_DEG_RIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_CIRCLE_45_DEG_LEFT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_CIRCLE_90_DEG_RIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_CIRCLE_90_DEG_LEFT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_CIRCLE_135_DEG_RIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_CIRCLE_135_DEG_LEFT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_CIRCLE_180_DEG: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_KEEP_LEFT_TO_TURN_0_DEG: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_KEEP_RIGHT_TO_TURN_0_DEG: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_KEEP_LEFT_TO_TURN_90_DEG_RIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_KEEP_RIGHT_TO_TURN_90_DEG_LEFT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_KEEP_LEFT_DRIVE_BACK_TO_TURN_90_DEG_RIGHT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                    DIRECTION_KEEP_RIGHT_DRIVE_BACK_TO_TURN_90_DEG_LEFT: _ClassVar[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                DIRECTION_UNKNOWN: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_OTHER: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_NO_DIRECTION: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_DIRECT_0_DEG: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_DIRECT_45_DEG_RIGHT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_DIRECT_45_DEG_LEFT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_DIRECT_90_DEG_RIGHT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_DIRECT_90_DEG_LEFT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_DIRECT_135_DEG_RIGHT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_DIRECT_135_DEG_LEFT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_DIRECT_180_DEG: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_TURN_45_DEG_RIGHT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_TURN_45_DEG_LEFT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_TURN_90_DEG_RIGHT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_TURN_90_DEG_LEFT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_TURN_135_DEG_RIGHT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_TURN_135_DEG_LEFT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_TURN_180_DEG_RIGHT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_TURN_180_DEG_LEFT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_CIRCLE_0_DEG: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_CIRCLE_45_DEG_RIGHT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_CIRCLE_45_DEG_LEFT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_CIRCLE_90_DEG_RIGHT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_CIRCLE_90_DEG_LEFT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_CIRCLE_135_DEG_RIGHT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_CIRCLE_135_DEG_LEFT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_CIRCLE_180_DEG: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_KEEP_LEFT_TO_TURN_0_DEG: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_KEEP_RIGHT_TO_TURN_0_DEG: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_KEEP_LEFT_TO_TURN_90_DEG_RIGHT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_KEEP_RIGHT_TO_TURN_90_DEG_LEFT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_KEEP_LEFT_DRIVE_BACK_TO_TURN_90_DEG_RIGHT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                DIRECTION_KEEP_RIGHT_DRIVE_BACK_TO_TURN_90_DEG_LEFT: TrafficSign.SupplementarySign.Classification.Arrow.Direction
                LANE_ID_FIELD_NUMBER: _ClassVar[int]
                DIRECTION_FIELD_NUMBER: _ClassVar[int]
                lane_id: _containers.RepeatedCompositeFieldContainer[_osi_common_pb2.Identifier]
                direction: _containers.RepeatedScalarFieldContainer[TrafficSign.SupplementarySign.Classification.Arrow.Direction]
                def __init__(self, lane_id: _Optional[_Iterable[_Union[_osi_common_pb2.Identifier, _Mapping]]] = ..., direction: _Optional[_Iterable[_Union[TrafficSign.SupplementarySign.Classification.Arrow.Direction, str]]] = ...) -> None: ...
            VARIABILITY_FIELD_NUMBER: _ClassVar[int]
            TYPE_FIELD_NUMBER: _ClassVar[int]
            VALUE_FIELD_NUMBER: _ClassVar[int]
            ASSIGNED_LANE_ID_FIELD_NUMBER: _ClassVar[int]
            ACTOR_FIELD_NUMBER: _ClassVar[int]
            ARROW_FIELD_NUMBER: _ClassVar[int]
            IS_OUT_OF_SERVICE_FIELD_NUMBER: _ClassVar[int]
            COUNTRY_FIELD_NUMBER: _ClassVar[int]
            COUNTRY_REVISION_FIELD_NUMBER: _ClassVar[int]
            CODE_FIELD_NUMBER: _ClassVar[int]
            SUB_CODE_FIELD_NUMBER: _ClassVar[int]
            LOGICAL_LANE_ASSIGNMENT_FIELD_NUMBER: _ClassVar[int]
            variability: TrafficSign.Variability
            type: TrafficSign.SupplementarySign.Classification.Type
            value: _containers.RepeatedCompositeFieldContainer[TrafficSignValue]
            assigned_lane_id: _containers.RepeatedCompositeFieldContainer[_osi_common_pb2.Identifier]
            actor: _containers.RepeatedScalarFieldContainer[TrafficSign.SupplementarySign.Classification.Actor]
            arrow: _containers.RepeatedCompositeFieldContainer[TrafficSign.SupplementarySign.Classification.Arrow]
            is_out_of_service: bool
            country: str
            country_revision: str
            code: str
            sub_code: str
            logical_lane_assignment: _containers.RepeatedCompositeFieldContainer[_osi_common_pb2.LogicalLaneAssignment]
            def __init__(self, variability: _Optional[_Union[TrafficSign.Variability, str]] = ..., type: _Optional[_Union[TrafficSign.SupplementarySign.Classification.Type, str]] = ..., value: _Optional[_Iterable[_Union[TrafficSignValue, _Mapping]]] = ..., assigned_lane_id: _Optional[_Iterable[_Union[_osi_common_pb2.Identifier, _Mapping]]] = ..., actor: _Optional[_Iterable[_Union[TrafficSign.SupplementarySign.Classification.Actor, str]]] = ..., arrow: _Optional[_Iterable[_Union[TrafficSign.SupplementarySign.Classification.Arrow, _Mapping]]] = ..., is_out_of_service: bool = ..., country: _Optional[str] = ..., country_revision: _Optional[str] = ..., code: _Optional[str] = ..., sub_code: _Optional[str] = ..., logical_lane_assignment: _Optional[_Iterable[_Union[_osi_common_pb2.LogicalLaneAssignment, _Mapping]]] = ...) -> None: ...
        BASE_FIELD_NUMBER: _ClassVar[int]
        CLASSIFICATION_FIELD_NUMBER: _ClassVar[int]
        MODEL_REFERENCE_FIELD_NUMBER: _ClassVar[int]
        base: _osi_common_pb2.BaseStationary
        classification: TrafficSign.SupplementarySign.Classification
        model_reference: str
        def __init__(self, base: _Optional[_Union[_osi_common_pb2.BaseStationary, _Mapping]] = ..., classification: _Optional[_Union[TrafficSign.SupplementarySign.Classification, _Mapping]] = ..., model_reference: _Optional[str] = ...) -> None: ...
    ID_FIELD_NUMBER: _ClassVar[int]
    MAIN_SIGN_FIELD_NUMBER: _ClassVar[int]
    SUPPLEMENTARY_SIGN_FIELD_NUMBER: _ClassVar[int]
    SOURCE_REFERENCE_FIELD_NUMBER: _ClassVar[int]
    id: _osi_common_pb2.Identifier
    main_sign: TrafficSign.MainSign
    supplementary_sign: _containers.RepeatedCompositeFieldContainer[TrafficSign.SupplementarySign]
    source_reference: _containers.RepeatedCompositeFieldContainer[_osi_common_pb2.ExternalReference]
    def __init__(self, id: _Optional[_Union[_osi_common_pb2.Identifier, _Mapping]] = ..., main_sign: _Optional[_Union[TrafficSign.MainSign, _Mapping]] = ..., supplementary_sign: _Optional[_Iterable[_Union[TrafficSign.SupplementarySign, _Mapping]]] = ..., source_reference: _Optional[_Iterable[_Union[_osi_common_pb2.ExternalReference, _Mapping]]] = ...) -> None: ...
